
//input ports
add mapped point clk clk -type PI PI
add mapped point rst_n rst_n -type PI PI

//output ports

//inout ports




//Sequential Pins
add mapped point u_ax/value_o[0]/q u_ax/value_o_reg[0]/Q -type DFF DFF
add mapped point u_ax/value_o[1]/q u_ax/value_o_reg[1]/Q -type DFF DFF
add mapped point u_ax/value_o[2]/q u_ax/value_o_reg[2]/Q -type DFF DFF
add mapped point u_ax/value_o[3]/q u_ax/value_o_reg[3]/Q -type DFF DFF
add mapped point u_ax/value_o[4]/q u_ax/value_o_reg[4]/Q -type DFF DFF
add mapped point u_ax/value_o[5]/q u_ax/value_o_reg[5]/Q -type DFF DFF
add mapped point u_ax/value_o[6]/q u_ax/value_o_reg[6]/Q -type DFF DFF
add mapped point u_ax/value_o[7]/q u_ax/value_o_reg[7]/Q -type DFF DFF
add mapped point u_ax/value_o[8]/q u_ax/value_o_reg[8]/Q -type DFF DFF
add mapped point u_ax/value_o[9]/q u_ax/value_o_reg[9]/Q -type DFF DFF
add mapped point u_ax/value_o[10]/q u_ax/value_o_reg[10]/Q -type DFF DFF
add mapped point u_ax/value_o[11]/q u_ax/value_o_reg[11]/Q -type DFF DFF
add mapped point u_ax/value_o[12]/q u_ax/value_o_reg[12]/Q -type DFF DFF
add mapped point u_ax/value_o[13]/q u_ax/value_o_reg[13]/Q -type DFF DFF
add mapped point u_ax/value_o[14]/q u_ax/value_o_reg[14]/Q -type DFF DFF
add mapped point u_ax/value_o[15]/q u_ax/value_o_reg[15]/Q -type DFF DFF
add mapped point u_ax/value_o[16]/q u_ax/value_o_reg[16]/Q -type DFF DFF
add mapped point u_ax/value_o[17]/q u_ax/value_o_reg[17]/Q -type DFF DFF
add mapped point u_ax/value_o[18]/q u_ax/value_o_reg[18]/Q -type DFF DFF
add mapped point u_ax/value_o[19]/q u_ax/value_o_reg[19]/Q -type DFF DFF
add mapped point u_ax/value_o[20]/q u_ax/value_o_reg[20]/Q -type DFF DFF
add mapped point u_ax/value_o[21]/q u_ax/value_o_reg[21]/Q -type DFF DFF
add mapped point u_ax/value_o[22]/q u_ax/value_o_reg[22]/Q -type DFF DFF
add mapped point u_ax/value_o[23]/q u_ax/value_o_reg[23]/Q -type DFF DFF
add mapped point u_ay/value_o[0]/q u_ay/value_o_reg[0]/Q -type DFF DFF
add mapped point u_ay/value_o[1]/q u_ay/value_o_reg[1]/Q -type DFF DFF
add mapped point u_ay/value_o[2]/q u_ay/value_o_reg[2]/Q -type DFF DFF
add mapped point u_ay/value_o[3]/q u_ay/value_o_reg[3]/Q -type DFF DFF
add mapped point u_ay/value_o[4]/q u_ay/value_o_reg[4]/Q -type DFF DFF
add mapped point u_ay/value_o[5]/q u_ay/value_o_reg[5]/Q -type DFF DFF
add mapped point u_ay/value_o[6]/q u_ay/value_o_reg[6]/Q -type DFF DFF
add mapped point u_ay/value_o[7]/q u_ay/value_o_reg[7]/Q -type DFF DFF
add mapped point u_ay/value_o[8]/q u_ay/value_o_reg[8]/Q -type DFF DFF
add mapped point u_ay/value_o[9]/q u_ay/value_o_reg[9]/Q -type DFF DFF
add mapped point u_ay/value_o[10]/q u_ay/value_o_reg[10]/Q -type DFF DFF
add mapped point u_ay/value_o[11]/q u_ay/value_o_reg[11]/Q -type DFF DFF
add mapped point u_ay/value_o[12]/q u_ay/value_o_reg[12]/Q -type DFF DFF
add mapped point u_ay/value_o[13]/q u_ay/value_o_reg[13]/Q -type DFF DFF
add mapped point u_ay/value_o[14]/q u_ay/value_o_reg[14]/Q -type DFF DFF
add mapped point u_ay/value_o[15]/q u_ay/value_o_reg[15]/Q -type DFF DFF
add mapped point u_ay/value_o[16]/q u_ay/value_o_reg[16]/Q -type DFF DFF
add mapped point u_ay/value_o[17]/q u_ay/value_o_reg[17]/Q -type DFF DFF
add mapped point u_ay/value_o[18]/q u_ay/value_o_reg[18]/Q -type DFF DFF
add mapped point u_ay/value_o[19]/q u_ay/value_o_reg[19]/Q -type DFF DFF
add mapped point u_ay/value_o[20]/q u_ay/value_o_reg[20]/Q -type DFF DFF
add mapped point u_ay/value_o[21]/q u_ay/value_o_reg[21]/Q -type DFF DFF
add mapped point u_ay/value_o[22]/q u_ay/value_o_reg[22]/Q -type DFF DFF
add mapped point u_ay/value_o[23]/q u_ay/value_o_reg[23]/Q -type DFF DFF
add mapped point u_dsp/u_adj/addr[0]/q u_dsp/u_adj/addr_reg[0]/Q -type DFF DFF
add mapped point u_dsp/u_adj/addr[1]/q u_dsp/u_adj/addr_reg[1]/Q -type DFF DFF
add mapped point u_dsp/u_adj/addr[2]/q u_dsp/u_adj/addr_reg[2]/Q -type DFF DFF
add mapped point u_dsp/u_adj/addr[3]/q u_dsp/u_adj/addr_reg[3]/Q -type DFF DFF
add mapped point u_dsp/u_adj/addr[4]/q u_dsp/u_adj/addr_reg[4]/Q -type DFF DFF
add mapped point u_dsp/u_adj/addr[5]/q u_dsp/u_adj/addr_reg[5]/Q -type DFF DFF
add mapped point u_dsp/u_adj/addr[6]/q u_dsp/u_adj/addr_reg[6]/Q -type DFF DFF
add mapped point u_dsp/u_adj/addr[7]/q u_dsp/u_adj/addr_reg[7]/Q -type DFF DFF
add mapped point u_dsp/u_adj/addr[8]/q u_dsp/u_adj/addr_reg[8]/Q -type DFF DFF
add mapped point u_dsp/u_adj/addr[9]/q u_dsp/u_adj/addr_reg[9]/Q -type DFF DFF
add mapped point u_dsp/u_adj/addr[10]/q u_dsp/u_adj/addr_reg[10]/Q -type DFF DFF
add mapped point u_dsp/u_adj/addr[11]/q u_dsp/u_adj/addr_reg[11]/Q -type DFF DFF
add mapped point u_dsp/u_adj/addr[12]/q u_dsp/u_adj/addr_reg[12]/Q -type DFF DFF
add mapped point u_dsp/u_adj/addr[13]/q u_dsp/u_adj/addr_reg[13]/Q -type DFF DFF
add mapped point u_dsp/u_adj/addr[14]/q u_dsp/u_adj/addr_reg[14]/Q -type DFF DFF
add mapped point u_dsp/u_adj/addr[15]/q u_dsp/u_adj/addr_reg[15]/Q -type DFF DFF
add mapped point u_dsp/u_adj/busy/q u_dsp/u_adj/busy_reg/Q -type DFF DFF
add mapped point u_dsp/u_adj/idx[0]/q u_dsp/u_adj/idx_reg[0]/Q -type DFF DFF
add mapped point u_dsp/u_adj/idx[1]/q u_dsp/u_adj/idx_reg[1]/Q -type DFF DFF
add mapped point u_dsp/req_busy/q u_dsp/req_busy_reg/Q -type DFF DFF
add mapped point u_dsp/pre_lat[0]/q u_dsp/pre_lat_reg[0]/Q -type DFF DFF
add mapped point u_dsp/pre_lat[1]/q u_dsp/pre_lat_reg[1]/Q -type DFF DFF
add mapped point u_mdec/east_o/q u_mdec/east_o_reg/Q -type DFF DFF
add mapped point u_mdec/north_o/q u_mdec/north_o_reg/Q -type DFF DFF
add mapped point u_mdec/south_o/q u_mdec/south_o_reg/Q -type DFF DFF
add mapped point u_mdec/west_o/q u_mdec/west_o_reg/Q -type DFF DFF
add mapped point u_mon/G_RATE[0].u_lp/rate_o[8]/q u_mon/G_RATE[0].u_lp/rate_o_reg[8]/Q -type DFF DFF
add mapped point u_mon/G_RATE[0].u_lp/rate_o[1]/q u_mon/G_RATE[0].u_lp/rate_o_reg[1]/Q -type DFF DFF
add mapped point u_mon/G_RATE[0].u_lp/rate_o[6]/q u_mon/G_RATE[0].u_lp/rate_o_reg[6]/Q -type DFF DFF
add mapped point u_mon/G_RATE[0].u_lp/rate_o[7]/q u_mon/G_RATE[0].u_lp/rate_o_reg[7]/Q -type DFF DFF
add mapped point u_mon/G_RATE[0].u_lp/rate_o[0]/q u_mon/G_RATE[0].u_lp/rate_o_reg[0]/Q -type DFF DFF
add mapped point u_mon/G_RATE[0].u_lp/rate_o[9]/q u_mon/G_RATE[0].u_lp/rate_o_reg[9]/Q -type DFF DFF
add mapped point u_mon/G_RATE[0].u_lp/rate_o[10]/q u_mon/G_RATE[0].u_lp/rate_o_reg[10]/Q -type DFF DFF
add mapped point u_mon/G_RATE[0].u_lp/rate_o[11]/q u_mon/G_RATE[0].u_lp/rate_o_reg[11]/Q -type DFF DFF
add mapped point u_mon/G_RATE[0].u_lp/rate_o[14]/q u_mon/G_RATE[0].u_lp/rate_o_reg[14]/Q -type DFF DFF
add mapped point u_mon/G_RATE[0].u_lp/rate_o[13]/q u_mon/G_RATE[0].u_lp/rate_o_reg[13]/Q -type DFF DFF
add mapped point u_mon/G_RATE[0].u_lp/rate_o[2]/q u_mon/G_RATE[0].u_lp/rate_o_reg[2]/Q -type DFF DFF
add mapped point u_mon/G_RATE[0].u_lp/rate_o[3]/q u_mon/G_RATE[0].u_lp/rate_o_reg[3]/Q -type DFF DFF
add mapped point u_mon/G_RATE[0].u_lp/rate_o[12]/q u_mon/G_RATE[0].u_lp/rate_o_reg[12]/Q -type DFF DFF
add mapped point u_mon/G_RATE[0].u_lp/rate_o[15]/q u_mon/G_RATE[0].u_lp/rate_o_reg[15]/Q -type DFF DFF
add mapped point u_mon/G_RATE[0].u_lp/rate_o[4]/q u_mon/G_RATE[0].u_lp/rate_o_reg[4]/Q -type DFF DFF
add mapped point u_mon/G_RATE[0].u_lp/rate_o[5]/q u_mon/G_RATE[0].u_lp/rate_o_reg[5]/Q -type DFF DFF
add mapped point u_mon/G_RATE[1].u_lp/rate_o[8]/q u_mon/G_RATE[1].u_lp/rate_o_reg[8]/Q -type DFF DFF
add mapped point u_mon/G_RATE[1].u_lp/rate_o[1]/q u_mon/G_RATE[1].u_lp/rate_o_reg[1]/Q -type DFF DFF
add mapped point u_mon/G_RATE[1].u_lp/rate_o[6]/q u_mon/G_RATE[1].u_lp/rate_o_reg[6]/Q -type DFF DFF
add mapped point u_mon/G_RATE[1].u_lp/rate_o[7]/q u_mon/G_RATE[1].u_lp/rate_o_reg[7]/Q -type DFF DFF
add mapped point u_mon/G_RATE[1].u_lp/rate_o[0]/q u_mon/G_RATE[1].u_lp/rate_o_reg[0]/Q -type DFF DFF
add mapped point u_mon/G_RATE[1].u_lp/rate_o[9]/q u_mon/G_RATE[1].u_lp/rate_o_reg[9]/Q -type DFF DFF
add mapped point u_mon/G_RATE[1].u_lp/rate_o[10]/q u_mon/G_RATE[1].u_lp/rate_o_reg[10]/Q -type DFF DFF
add mapped point u_mon/G_RATE[1].u_lp/rate_o[11]/q u_mon/G_RATE[1].u_lp/rate_o_reg[11]/Q -type DFF DFF
add mapped point u_mon/G_RATE[1].u_lp/rate_o[14]/q u_mon/G_RATE[1].u_lp/rate_o_reg[14]/Q -type DFF DFF
add mapped point u_mon/G_RATE[1].u_lp/rate_o[13]/q u_mon/G_RATE[1].u_lp/rate_o_reg[13]/Q -type DFF DFF
add mapped point u_mon/G_RATE[1].u_lp/rate_o[2]/q u_mon/G_RATE[1].u_lp/rate_o_reg[2]/Q -type DFF DFF
add mapped point u_mon/G_RATE[1].u_lp/rate_o[3]/q u_mon/G_RATE[1].u_lp/rate_o_reg[3]/Q -type DFF DFF
add mapped point u_mon/G_RATE[1].u_lp/rate_o[12]/q u_mon/G_RATE[1].u_lp/rate_o_reg[12]/Q -type DFF DFF
add mapped point u_mon/G_RATE[1].u_lp/rate_o[15]/q u_mon/G_RATE[1].u_lp/rate_o_reg[15]/Q -type DFF DFF
add mapped point u_mon/G_RATE[1].u_lp/rate_o[4]/q u_mon/G_RATE[1].u_lp/rate_o_reg[4]/Q -type DFF DFF
add mapped point u_mon/G_RATE[1].u_lp/rate_o[5]/q u_mon/G_RATE[1].u_lp/rate_o_reg[5]/Q -type DFF DFF
add mapped point u_mon/G_RATE[2].u_lp/rate_o[8]/q u_mon/G_RATE[2].u_lp/rate_o_reg[8]/Q -type DFF DFF
add mapped point u_mon/G_RATE[2].u_lp/rate_o[1]/q u_mon/G_RATE[2].u_lp/rate_o_reg[1]/Q -type DFF DFF
add mapped point u_mon/G_RATE[2].u_lp/rate_o[6]/q u_mon/G_RATE[2].u_lp/rate_o_reg[6]/Q -type DFF DFF
add mapped point u_mon/G_RATE[2].u_lp/rate_o[7]/q u_mon/G_RATE[2].u_lp/rate_o_reg[7]/Q -type DFF DFF
add mapped point u_mon/G_RATE[2].u_lp/rate_o[0]/q u_mon/G_RATE[2].u_lp/rate_o_reg[0]/Q -type DFF DFF
add mapped point u_mon/G_RATE[2].u_lp/rate_o[9]/q u_mon/G_RATE[2].u_lp/rate_o_reg[9]/Q -type DFF DFF
add mapped point u_mon/G_RATE[2].u_lp/rate_o[10]/q u_mon/G_RATE[2].u_lp/rate_o_reg[10]/Q -type DFF DFF
add mapped point u_mon/G_RATE[2].u_lp/rate_o[11]/q u_mon/G_RATE[2].u_lp/rate_o_reg[11]/Q -type DFF DFF
add mapped point u_mon/G_RATE[2].u_lp/rate_o[14]/q u_mon/G_RATE[2].u_lp/rate_o_reg[14]/Q -type DFF DFF
add mapped point u_mon/G_RATE[2].u_lp/rate_o[13]/q u_mon/G_RATE[2].u_lp/rate_o_reg[13]/Q -type DFF DFF
add mapped point u_mon/G_RATE[2].u_lp/rate_o[2]/q u_mon/G_RATE[2].u_lp/rate_o_reg[2]/Q -type DFF DFF
add mapped point u_mon/G_RATE[2].u_lp/rate_o[3]/q u_mon/G_RATE[2].u_lp/rate_o_reg[3]/Q -type DFF DFF
add mapped point u_mon/G_RATE[2].u_lp/rate_o[12]/q u_mon/G_RATE[2].u_lp/rate_o_reg[12]/Q -type DFF DFF
add mapped point u_mon/G_RATE[2].u_lp/rate_o[15]/q u_mon/G_RATE[2].u_lp/rate_o_reg[15]/Q -type DFF DFF
add mapped point u_mon/G_RATE[2].u_lp/rate_o[4]/q u_mon/G_RATE[2].u_lp/rate_o_reg[4]/Q -type DFF DFF
add mapped point u_mon/G_RATE[2].u_lp/rate_o[5]/q u_mon/G_RATE[2].u_lp/rate_o_reg[5]/Q -type DFF DFF
add mapped point u_mon/dbg_status[0]/q u_mon/dbg_status_reg[0]/Q -type DFF DFF
add mapped point u_mon/dbg_status[1]/q u_mon/dbg_status_reg[1]/Q -type DFF DFF
add mapped point u_mon/dbg_status[7]/q u_mon/dbg_status_reg[7]/Q -type DFF DFF
add mapped point u_mon/dbg_status[8]/q u_mon/dbg_status_reg[8]/Q -type DFF DFF
add mapped point u_mon/dbg_status[9]/q u_mon/dbg_status_reg[9]/Q -type DFF DFF
add mapped point u_mon/dbg_status[10]/q u_mon/dbg_status_reg[10]/Q -type DFF DFF
add mapped point u_mon/dbg_status[2]/q u_mon/dbg_status_reg[2]/Q -type DFF DFF
add mapped point u_mon/dbg_status[11]/q u_mon/dbg_status_reg[11]/Q -type DFF DFF
add mapped point u_mon/dbg_status[3]/q u_mon/dbg_status_reg[3]/Q -type DFF DFF
add mapped point u_mon/dbg_status[4]/q u_mon/dbg_status_reg[4]/Q -type DFF DFF
add mapped point u_mon/dbg_status[5]/q u_mon/dbg_status_reg[5]/Q -type DFF DFF
add mapped point u_mon/dbg_status[6]/q u_mon/dbg_status_reg[6]/Q -type DFF DFF
add mapped point u_mon/dopamine_o[6]/q u_mon/dopamine_o_reg[6]/Q -type DFF DFF
add mapped point u_mon/dopamine_o[7]/q u_mon/dopamine_o_reg[7]/Q -type DFF DFF
add mapped point u_phy/u_lx/r[31]/q u_phy/u_lx/r_reg[31]/Q -type DFF DFF
add mapped point u_phy/u_lx/r[30]/q u_phy/u_lx/r_reg[30]/Q -type DFF DFF
add mapped point u_phy/u_lx/r[29]/q u_phy/u_lx/r_reg[29]/Q -type DFF DFF
add mapped point u_phy/u_lx/r[28]/q u_phy/u_lx/r_reg[28]/Q -type DFF DFF
add mapped point u_phy/u_lx/r[27]/q u_phy/u_lx/r_reg[27]/Q -type DFF DFF
add mapped point u_phy/u_lx/r[26]/q u_phy/u_lx/r_reg[26]/Q -type DFF DFF
add mapped point u_phy/u_lx/r[25]/q u_phy/u_lx/r_reg[25]/Q -type DFF DFF
add mapped point u_phy/u_lx/r[24]/q u_phy/u_lx/r_reg[24]/Q -type DFF DFF
add mapped point u_phy/u_lx/r[23]/q u_phy/u_lx/r_reg[23]/Q -type DFF DFF
add mapped point u_phy/u_lx/r[22]/q u_phy/u_lx/r_reg[22]/Q -type DFF DFF
add mapped point u_phy/u_lx/r[21]/q u_phy/u_lx/r_reg[21]/Q -type DFF DFF
add mapped point u_phy/u_lx/r[20]/q u_phy/u_lx/r_reg[20]/Q -type DFF DFF
add mapped point u_phy/u_lx/r[19]/q u_phy/u_lx/r_reg[19]/Q -type DFF DFF
add mapped point u_phy/u_lx/r[18]/q u_phy/u_lx/r_reg[18]/Q -type DFF DFF
add mapped point u_phy/u_lx/r[17]/q u_phy/u_lx/r_reg[17]/Q -type DFF DFF
add mapped point u_phy/u_lx/r[16]/q u_phy/u_lx/r_reg[16]/Q -type DFF DFF
add mapped point u_phy/u_lx/r[15]/q u_phy/u_lx/r_reg[15]/Q -type DFF DFF
add mapped point u_phy/u_lx/r[14]/q u_phy/u_lx/r_reg[14]/Q -type DFF DFF
add mapped point u_phy/u_lx/r[13]/q u_phy/u_lx/r_reg[13]/Q -type DFF DFF
add mapped point u_phy/u_lx/r[12]/q u_phy/u_lx/r_reg[12]/Q -type DFF DFF
add mapped point u_phy/u_lx/r[11]/q u_phy/u_lx/r_reg[11]/Q -type DFF DFF
add mapped point u_phy/u_lx/r[10]/q u_phy/u_lx/r_reg[10]/Q -type DFF DFF
add mapped point u_phy/u_lx/r[9]/q u_phy/u_lx/r_reg[9]/Q -type DFF DFF
add mapped point u_phy/u_lx/r[8]/q u_phy/u_lx/r_reg[8]/Q -type DFF DFF
add mapped point u_phy/u_lx/r[7]/q u_phy/u_lx/r_reg[7]/Q -type DFF DFF
add mapped point u_phy/u_lx/r[6]/q u_phy/u_lx/r_reg[6]/Q -type DFF DFF
add mapped point u_phy/u_lx/r[5]/q u_phy/u_lx/r_reg[5]/Q -type DFF DFF
add mapped point u_phy/u_lx/r[4]/q u_phy/u_lx/r_reg[4]/Q -type DFF DFF
add mapped point u_phy/u_lx/r[3]/q u_phy/u_lx/r_reg[3]/Q -type DFF DFF
add mapped point u_phy/u_lx/r[2]/q u_phy/u_lx/r_reg[2]/Q -type DFF DFF
add mapped point u_phy/u_lx/r[1]/q u_phy/u_lx/r_reg[1]/Q -type DFF DFF
add mapped point u_phy/u_lx/r[0]/q u_phy/u_lx/r_reg[0]/Q -type DFF DFF
add mapped point u_phy/u_ly/r[31]/q u_phy/u_ly/r_reg[31]/Q -type DFF DFF
add mapped point u_phy/u_ly/r[30]/q u_phy/u_ly/r_reg[30]/Q -type DFF DFF
add mapped point u_phy/u_ly/r[29]/q u_phy/u_ly/r_reg[29]/Q -type DFF DFF
add mapped point u_phy/u_ly/r[28]/q u_phy/u_ly/r_reg[28]/Q -type DFF DFF
add mapped point u_phy/u_ly/r[27]/q u_phy/u_ly/r_reg[27]/Q -type DFF DFF
add mapped point u_phy/u_ly/r[26]/q u_phy/u_ly/r_reg[26]/Q -type DFF DFF
add mapped point u_phy/u_ly/r[25]/q u_phy/u_ly/r_reg[25]/Q -type DFF DFF
add mapped point u_phy/u_ly/r[24]/q u_phy/u_ly/r_reg[24]/Q -type DFF DFF
add mapped point u_phy/u_ly/r[23]/q u_phy/u_ly/r_reg[23]/Q -type DFF DFF
add mapped point u_phy/u_ly/r[22]/q u_phy/u_ly/r_reg[22]/Q -type DFF DFF
add mapped point u_phy/u_ly/r[21]/q u_phy/u_ly/r_reg[21]/Q -type DFF DFF
add mapped point u_phy/u_ly/r[20]/q u_phy/u_ly/r_reg[20]/Q -type DFF DFF
add mapped point u_phy/u_ly/r[19]/q u_phy/u_ly/r_reg[19]/Q -type DFF DFF
add mapped point u_phy/u_ly/r[18]/q u_phy/u_ly/r_reg[18]/Q -type DFF DFF
add mapped point u_phy/u_ly/r[17]/q u_phy/u_ly/r_reg[17]/Q -type DFF DFF
add mapped point u_phy/u_ly/r[16]/q u_phy/u_ly/r_reg[16]/Q -type DFF DFF
add mapped point u_phy/u_ly/r[15]/q u_phy/u_ly/r_reg[15]/Q -type DFF DFF
add mapped point u_phy/u_ly/r[14]/q u_phy/u_ly/r_reg[14]/Q -type DFF DFF
add mapped point u_phy/u_ly/r[13]/q u_phy/u_ly/r_reg[13]/Q -type DFF DFF
add mapped point u_phy/u_ly/r[12]/q u_phy/u_ly/r_reg[12]/Q -type DFF DFF
add mapped point u_phy/u_ly/r[11]/q u_phy/u_ly/r_reg[11]/Q -type DFF DFF
add mapped point u_phy/u_ly/r[10]/q u_phy/u_ly/r_reg[10]/Q -type DFF DFF
add mapped point u_phy/u_ly/r[9]/q u_phy/u_ly/r_reg[9]/Q -type DFF DFF
add mapped point u_phy/u_ly/r[8]/q u_phy/u_ly/r_reg[8]/Q -type DFF DFF
add mapped point u_phy/u_ly/r[7]/q u_phy/u_ly/r_reg[7]/Q -type DFF DFF
add mapped point u_phy/u_ly/r[6]/q u_phy/u_ly/r_reg[6]/Q -type DFF DFF
add mapped point u_phy/u_ly/r[5]/q u_phy/u_ly/r_reg[5]/Q -type DFF DFF
add mapped point u_phy/u_ly/r[4]/q u_phy/u_ly/r_reg[4]/Q -type DFF DFF
add mapped point u_phy/u_ly/r[3]/q u_phy/u_ly/r_reg[3]/Q -type DFF DFF
add mapped point u_phy/u_ly/r[2]/q u_phy/u_ly/r_reg[2]/Q -type DFF DFF
add mapped point u_phy/u_ly/r[1]/q u_phy/u_ly/r_reg[1]/Q -type DFF DFF
add mapped point u_phy/u_ly/r[0]/q u_phy/u_ly/r_reg[0]/Q -type DFF DFF
add mapped point u_phy/goal_reached_o/q u_phy/goal_reached_o_reg/Q -type DFF DFF
add mapped point u_phy/init_done/q u_phy/init_done_reg/Q -type DFF DFF
add mapped point u_phy/px_q[0]/q u_phy/px_q_reg[0]/Q -type DFF DFF
add mapped point u_phy/px_q[1]/q u_phy/px_q_reg[1]/Q -type DFF DFF
add mapped point u_phy/px_q[2]/q u_phy/px_q_reg[2]/Q -type DFF DFF
add mapped point u_phy/px_q[3]/q u_phy/px_q_reg[3]/Q -type DFF DFF
add mapped point u_phy/px_q[4]/q u_phy/px_q_reg[4]/Q -type DFF DFF
add mapped point u_phy/px_q[5]/q u_phy/px_q_reg[5]/Q -type DFF DFF
add mapped point u_phy/px_q[6]/q u_phy/px_q_reg[6]/Q -type DFF DFF
add mapped point u_phy/px_q[7]/q u_phy/px_q_reg[7]/Q -type DFF DFF
add mapped point u_phy/px_q[8]/q u_phy/px_q_reg[8]/Q -type DFF DFF
add mapped point u_phy/px_q[9]/q u_phy/px_q_reg[9]/Q -type DFF DFF
add mapped point u_phy/px_q[10]/q u_phy/px_q_reg[10]/Q -type DFF DFF
add mapped point u_phy/px_q[11]/q u_phy/px_q_reg[11]/Q -type DFF DFF
add mapped point u_phy/px_q[12]/q u_phy/px_q_reg[12]/Q -type DFF DFF
add mapped point u_phy/px_q[13]/q u_phy/px_q_reg[13]/Q -type DFF DFF
add mapped point u_phy/px_q[14]/q u_phy/px_q_reg[14]/Q -type DFF DFF
add mapped point u_phy/px_q[15]/q u_phy/px_q_reg[15]/Q -type DFF DFF
add mapped point u_phy/px_q[16]/q u_phy/px_q_reg[16]/Q -type DFF DFF
add mapped point u_phy/px_q[17]/q u_phy/px_q_reg[17]/Q -type DFF DFF
add mapped point u_phy/px_q[18]/q u_phy/px_q_reg[18]/Q -type DFF DFF
add mapped point u_phy/px_q[19]/q u_phy/px_q_reg[19]/Q -type DFF DFF
add mapped point u_phy/px_q[20]/q u_phy/px_q_reg[20]/Q -type DFF DFF
add mapped point u_phy/px_q[21]/q u_phy/px_q_reg[21]/Q -type DFF DFF
add mapped point u_phy/px_q[22]/q u_phy/px_q_reg[22]/Q -type DFF DFF
add mapped point u_phy/px_q[23]/q u_phy/px_q_reg[23]/Q -type DFF DFF
add mapped point u_phy/px_q[24]/q u_phy/px_q_reg[24]/Q -type DFF DFF
add mapped point u_phy/px_q[25]/q u_phy/px_q_reg[25]/Q -type DFF DFF
add mapped point u_phy/px_q[26]/q u_phy/px_q_reg[26]/Q -type DFF DFF
add mapped point u_phy/px_q[27]/q u_phy/px_q_reg[27]/Q -type DFF DFF
add mapped point u_phy/px_q[28]/q u_phy/px_q_reg[28]/Q -type DFF DFF
add mapped point u_phy/px_q[29]/q u_phy/px_q_reg[29]/Q -type DFF DFF
add mapped point u_phy/px_q[30]/q u_phy/px_q_reg[30]/Q -type DFF DFF
add mapped point u_phy/px_q[31]/q u_phy/px_q_reg[31]/Q -type DFF DFF
add mapped point u_phy/py_q[0]/q u_phy/py_q_reg[0]/Q -type DFF DFF
add mapped point u_phy/py_q[1]/q u_phy/py_q_reg[1]/Q -type DFF DFF
add mapped point u_phy/py_q[2]/q u_phy/py_q_reg[2]/Q -type DFF DFF
add mapped point u_phy/py_q[3]/q u_phy/py_q_reg[3]/Q -type DFF DFF
add mapped point u_phy/py_q[4]/q u_phy/py_q_reg[4]/Q -type DFF DFF
add mapped point u_phy/py_q[5]/q u_phy/py_q_reg[5]/Q -type DFF DFF
add mapped point u_phy/py_q[6]/q u_phy/py_q_reg[6]/Q -type DFF DFF
add mapped point u_phy/py_q[7]/q u_phy/py_q_reg[7]/Q -type DFF DFF
add mapped point u_phy/py_q[8]/q u_phy/py_q_reg[8]/Q -type DFF DFF
add mapped point u_phy/py_q[9]/q u_phy/py_q_reg[9]/Q -type DFF DFF
add mapped point u_phy/py_q[10]/q u_phy/py_q_reg[10]/Q -type DFF DFF
add mapped point u_phy/py_q[11]/q u_phy/py_q_reg[11]/Q -type DFF DFF
add mapped point u_phy/py_q[12]/q u_phy/py_q_reg[12]/Q -type DFF DFF
add mapped point u_phy/py_q[13]/q u_phy/py_q_reg[13]/Q -type DFF DFF
add mapped point u_phy/py_q[14]/q u_phy/py_q_reg[14]/Q -type DFF DFF
add mapped point u_phy/py_q[15]/q u_phy/py_q_reg[15]/Q -type DFF DFF
add mapped point u_phy/py_q[16]/q u_phy/py_q_reg[16]/Q -type DFF DFF
add mapped point u_phy/py_q[17]/q u_phy/py_q_reg[17]/Q -type DFF DFF
add mapped point u_phy/py_q[18]/q u_phy/py_q_reg[18]/Q -type DFF DFF
add mapped point u_phy/py_q[19]/q u_phy/py_q_reg[19]/Q -type DFF DFF
add mapped point u_phy/py_q[20]/q u_phy/py_q_reg[20]/Q -type DFF DFF
add mapped point u_phy/py_q[21]/q u_phy/py_q_reg[21]/Q -type DFF DFF
add mapped point u_phy/py_q[22]/q u_phy/py_q_reg[22]/Q -type DFF DFF
add mapped point u_phy/py_q[23]/q u_phy/py_q_reg[23]/Q -type DFF DFF
add mapped point u_phy/py_q[24]/q u_phy/py_q_reg[24]/Q -type DFF DFF
add mapped point u_phy/py_q[25]/q u_phy/py_q_reg[25]/Q -type DFF DFF
add mapped point u_phy/py_q[26]/q u_phy/py_q_reg[26]/Q -type DFF DFF
add mapped point u_phy/py_q[27]/q u_phy/py_q_reg[27]/Q -type DFF DFF
add mapped point u_phy/py_q[28]/q u_phy/py_q_reg[28]/Q -type DFF DFF
add mapped point u_phy/py_q[29]/q u_phy/py_q_reg[29]/Q -type DFF DFF
add mapped point u_phy/py_q[30]/q u_phy/py_q_reg[30]/Q -type DFF DFF
add mapped point u_phy/py_q[31]/q u_phy/py_q_reg[31]/Q -type DFF DFF
add mapped point u_phy/vx_q[0]/q u_phy/vx_q_reg[0]/Q -type DFF DFF
add mapped point u_phy/vx_q[1]/q u_phy/vx_q_reg[1]/Q -type DFF DFF
add mapped point u_phy/vx_q[2]/q u_phy/vx_q_reg[2]/Q -type DFF DFF
add mapped point u_phy/vx_q[3]/q u_phy/vx_q_reg[3]/Q -type DFF DFF
add mapped point u_phy/vx_q[4]/q u_phy/vx_q_reg[4]/Q -type DFF DFF
add mapped point u_phy/vx_q[5]/q u_phy/vx_q_reg[5]/Q -type DFF DFF
add mapped point u_phy/vx_q[6]/q u_phy/vx_q_reg[6]/Q -type DFF DFF
add mapped point u_phy/vx_q[7]/q u_phy/vx_q_reg[7]/Q -type DFF DFF
add mapped point u_phy/vx_q[8]/q u_phy/vx_q_reg[8]/Q -type DFF DFF
add mapped point u_phy/vx_q[9]/q u_phy/vx_q_reg[9]/Q -type DFF DFF
add mapped point u_phy/vx_q[10]/q u_phy/vx_q_reg[10]/Q -type DFF DFF
add mapped point u_phy/vx_q[11]/q u_phy/vx_q_reg[11]/Q -type DFF DFF
add mapped point u_phy/vx_q[12]/q u_phy/vx_q_reg[12]/Q -type DFF DFF
add mapped point u_phy/vx_q[13]/q u_phy/vx_q_reg[13]/Q -type DFF DFF
add mapped point u_phy/vx_q[14]/q u_phy/vx_q_reg[14]/Q -type DFF DFF
add mapped point u_phy/vx_q[15]/q u_phy/vx_q_reg[15]/Q -type DFF DFF
add mapped point u_phy/vx_q[16]/q u_phy/vx_q_reg[16]/Q -type DFF DFF
add mapped point u_phy/vx_q[17]/q u_phy/vx_q_reg[17]/Q -type DFF DFF
add mapped point u_phy/vx_q[18]/q u_phy/vx_q_reg[18]/Q -type DFF DFF
add mapped point u_phy/vx_q[19]/q u_phy/vx_q_reg[19]/Q -type DFF DFF
add mapped point u_phy/vx_q[20]/q u_phy/vx_q_reg[20]/Q -type DFF DFF
add mapped point u_phy/vx_q[21]/q u_phy/vx_q_reg[21]/Q -type DFF DFF
add mapped point u_phy/vx_q[22]/q u_phy/vx_q_reg[22]/Q -type DFF DFF
add mapped point u_phy/vx_q[23]/q u_phy/vx_q_reg[23]/Q -type DFF DFF
add mapped point u_phy/vx_q[24]/q u_phy/vx_q_reg[24]/Q -type DFF DFF
add mapped point u_phy/vx_q[25]/q u_phy/vx_q_reg[25]/Q -type DFF DFF
add mapped point u_phy/vx_q[26]/q u_phy/vx_q_reg[26]/Q -type DFF DFF
add mapped point u_phy/vx_q[27]/q u_phy/vx_q_reg[27]/Q -type DFF DFF
add mapped point u_phy/vx_q[28]/q u_phy/vx_q_reg[28]/Q -type DFF DFF
add mapped point u_phy/vx_q[29]/q u_phy/vx_q_reg[29]/Q -type DFF DFF
add mapped point u_phy/vx_q[30]/q u_phy/vx_q_reg[30]/Q -type DFF DFF
add mapped point u_phy/vx_q[31]/q u_phy/vx_q_reg[31]/Q -type DFF DFF
add mapped point u_phy/vy_q[0]/q u_phy/vy_q_reg[0]/Q -type DFF DFF
add mapped point u_phy/vy_q[1]/q u_phy/vy_q_reg[1]/Q -type DFF DFF
add mapped point u_phy/vy_q[2]/q u_phy/vy_q_reg[2]/Q -type DFF DFF
add mapped point u_phy/vy_q[3]/q u_phy/vy_q_reg[3]/Q -type DFF DFF
add mapped point u_phy/vy_q[4]/q u_phy/vy_q_reg[4]/Q -type DFF DFF
add mapped point u_phy/vy_q[5]/q u_phy/vy_q_reg[5]/Q -type DFF DFF
add mapped point u_phy/vy_q[6]/q u_phy/vy_q_reg[6]/Q -type DFF DFF
add mapped point u_phy/vy_q[7]/q u_phy/vy_q_reg[7]/Q -type DFF DFF
add mapped point u_phy/vy_q[8]/q u_phy/vy_q_reg[8]/Q -type DFF DFF
add mapped point u_phy/vy_q[9]/q u_phy/vy_q_reg[9]/Q -type DFF DFF
add mapped point u_phy/vy_q[10]/q u_phy/vy_q_reg[10]/Q -type DFF DFF
add mapped point u_phy/vy_q[11]/q u_phy/vy_q_reg[11]/Q -type DFF DFF
add mapped point u_phy/vy_q[12]/q u_phy/vy_q_reg[12]/Q -type DFF DFF
add mapped point u_phy/vy_q[13]/q u_phy/vy_q_reg[13]/Q -type DFF DFF
add mapped point u_phy/vy_q[14]/q u_phy/vy_q_reg[14]/Q -type DFF DFF
add mapped point u_phy/vy_q[15]/q u_phy/vy_q_reg[15]/Q -type DFF DFF
add mapped point u_phy/vy_q[16]/q u_phy/vy_q_reg[16]/Q -type DFF DFF
add mapped point u_phy/vy_q[17]/q u_phy/vy_q_reg[17]/Q -type DFF DFF
add mapped point u_phy/vy_q[18]/q u_phy/vy_q_reg[18]/Q -type DFF DFF
add mapped point u_phy/vy_q[19]/q u_phy/vy_q_reg[19]/Q -type DFF DFF
add mapped point u_phy/vy_q[20]/q u_phy/vy_q_reg[20]/Q -type DFF DFF
add mapped point u_phy/vy_q[21]/q u_phy/vy_q_reg[21]/Q -type DFF DFF
add mapped point u_phy/vy_q[22]/q u_phy/vy_q_reg[22]/Q -type DFF DFF
add mapped point u_phy/vy_q[23]/q u_phy/vy_q_reg[23]/Q -type DFF DFF
add mapped point u_phy/vy_q[24]/q u_phy/vy_q_reg[24]/Q -type DFF DFF
add mapped point u_phy/vy_q[25]/q u_phy/vy_q_reg[25]/Q -type DFF DFF
add mapped point u_phy/vy_q[26]/q u_phy/vy_q_reg[26]/Q -type DFF DFF
add mapped point u_phy/vy_q[27]/q u_phy/vy_q_reg[27]/Q -type DFF DFF
add mapped point u_phy/vy_q[28]/q u_phy/vy_q_reg[28]/Q -type DFF DFF
add mapped point u_phy/vy_q[29]/q u_phy/vy_q_reg[29]/Q -type DFF DFF
add mapped point u_phy/vy_q[30]/q u_phy/vy_q_reg[30]/Q -type DFF DFF
add mapped point u_phy/vy_q[31]/q u_phy/vy_q_reg[31]/Q -type DFF DFF
add mapped point u_pwr/clk_en_o/q u_pwr/clk_en_o_reg/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/active_q[0]/q u_sens/G_SENS[0].u_tof/active_q_reg[0]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/active_q[1]/q u_sens/G_SENS[0].u_tof/active_q_reg[1]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/active_q[2]/q u_sens/G_SENS[0].u_tof/active_q_reg[2]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/active_q[3]/q u_sens/G_SENS[0].u_tof/active_q_reg[3]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/active_q[4]/q u_sens/G_SENS[0].u_tof/active_q_reg[4]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/active_q[5]/q u_sens/G_SENS[0].u_tof/active_q_reg[5]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/active_q[6]/q u_sens/G_SENS[0].u_tof/active_q_reg[6]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/active_q[7]/q u_sens/G_SENS[0].u_tof/active_q_reg[7]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/alloc_ptr_q[0]/q u_sens/G_SENS[0].u_tof/alloc_ptr_q_reg[0]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/alloc_ptr_q[1]/q u_sens/G_SENS[0].u_tof/alloc_ptr_q_reg[1]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/alloc_ptr_q[2]/q u_sens/G_SENS[0].u_tof/alloc_ptr_q_reg[2]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/cnt_q[0][0]/q u_sens/G_SENS[0].u_tof/cnt_q_reg[0][0]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/cnt_q[0][1]/q u_sens/G_SENS[0].u_tof/cnt_q_reg[0][1]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/cnt_q[0][2]/q u_sens/G_SENS[0].u_tof/cnt_q_reg[0][2]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/cnt_q[0][3]/q u_sens/G_SENS[0].u_tof/cnt_q_reg[0][3]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/cnt_q[0][4]/q u_sens/G_SENS[0].u_tof/cnt_q_reg[0][4]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/cnt_q[0][5]/q u_sens/G_SENS[0].u_tof/cnt_q_reg[0][5]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/cnt_q[1][0]/q u_sens/G_SENS[0].u_tof/cnt_q_reg[1][0]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/cnt_q[1][1]/q u_sens/G_SENS[0].u_tof/cnt_q_reg[1][1]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/cnt_q[1][2]/q u_sens/G_SENS[0].u_tof/cnt_q_reg[1][2]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/cnt_q[1][3]/q u_sens/G_SENS[0].u_tof/cnt_q_reg[1][3]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/cnt_q[1][4]/q u_sens/G_SENS[0].u_tof/cnt_q_reg[1][4]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/cnt_q[1][5]/q u_sens/G_SENS[0].u_tof/cnt_q_reg[1][5]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/cnt_q[2][0]/q u_sens/G_SENS[0].u_tof/cnt_q_reg[2][0]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/cnt_q[2][1]/q u_sens/G_SENS[0].u_tof/cnt_q_reg[2][1]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/cnt_q[2][2]/q u_sens/G_SENS[0].u_tof/cnt_q_reg[2][2]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/cnt_q[2][3]/q u_sens/G_SENS[0].u_tof/cnt_q_reg[2][3]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/cnt_q[2][4]/q u_sens/G_SENS[0].u_tof/cnt_q_reg[2][4]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/cnt_q[2][5]/q u_sens/G_SENS[0].u_tof/cnt_q_reg[2][5]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/cnt_q[3][0]/q u_sens/G_SENS[0].u_tof/cnt_q_reg[3][0]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/cnt_q[3][1]/q u_sens/G_SENS[0].u_tof/cnt_q_reg[3][1]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/cnt_q[3][2]/q u_sens/G_SENS[0].u_tof/cnt_q_reg[3][2]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/cnt_q[3][3]/q u_sens/G_SENS[0].u_tof/cnt_q_reg[3][3]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/cnt_q[3][4]/q u_sens/G_SENS[0].u_tof/cnt_q_reg[3][4]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/cnt_q[3][5]/q u_sens/G_SENS[0].u_tof/cnt_q_reg[3][5]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/cnt_q[4][0]/q u_sens/G_SENS[0].u_tof/cnt_q_reg[4][0]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/cnt_q[4][1]/q u_sens/G_SENS[0].u_tof/cnt_q_reg[4][1]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/cnt_q[4][2]/q u_sens/G_SENS[0].u_tof/cnt_q_reg[4][2]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/cnt_q[4][3]/q u_sens/G_SENS[0].u_tof/cnt_q_reg[4][3]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/cnt_q[4][4]/q u_sens/G_SENS[0].u_tof/cnt_q_reg[4][4]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/cnt_q[4][5]/q u_sens/G_SENS[0].u_tof/cnt_q_reg[4][5]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/cnt_q[5][0]/q u_sens/G_SENS[0].u_tof/cnt_q_reg[5][0]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/cnt_q[5][1]/q u_sens/G_SENS[0].u_tof/cnt_q_reg[5][1]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/cnt_q[5][2]/q u_sens/G_SENS[0].u_tof/cnt_q_reg[5][2]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/cnt_q[5][3]/q u_sens/G_SENS[0].u_tof/cnt_q_reg[5][3]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/cnt_q[5][4]/q u_sens/G_SENS[0].u_tof/cnt_q_reg[5][4]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/cnt_q[5][5]/q u_sens/G_SENS[0].u_tof/cnt_q_reg[5][5]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/cnt_q[6][0]/q u_sens/G_SENS[0].u_tof/cnt_q_reg[6][0]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/cnt_q[6][1]/q u_sens/G_SENS[0].u_tof/cnt_q_reg[6][1]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/cnt_q[6][2]/q u_sens/G_SENS[0].u_tof/cnt_q_reg[6][2]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/cnt_q[6][3]/q u_sens/G_SENS[0].u_tof/cnt_q_reg[6][3]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/cnt_q[6][4]/q u_sens/G_SENS[0].u_tof/cnt_q_reg[6][4]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/cnt_q[6][5]/q u_sens/G_SENS[0].u_tof/cnt_q_reg[6][5]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/cnt_q[7][0]/q u_sens/G_SENS[0].u_tof/cnt_q_reg[7][0]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/cnt_q[7][1]/q u_sens/G_SENS[0].u_tof/cnt_q_reg[7][1]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/cnt_q[7][2]/q u_sens/G_SENS[0].u_tof/cnt_q_reg[7][2]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/cnt_q[7][3]/q u_sens/G_SENS[0].u_tof/cnt_q_reg[7][3]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/cnt_q[7][4]/q u_sens/G_SENS[0].u_tof/cnt_q_reg[7][4]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/cnt_q[7][5]/q u_sens/G_SENS[0].u_tof/cnt_q_reg[7][5]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].u_tof/out_pulse/q u_sens/G_SENS[0].u_tof/out_pulse_reg/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/active_q[0]/q u_sens/G_SENS[1].u_tof/active_q_reg[0]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/active_q[1]/q u_sens/G_SENS[1].u_tof/active_q_reg[1]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/active_q[2]/q u_sens/G_SENS[1].u_tof/active_q_reg[2]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/active_q[3]/q u_sens/G_SENS[1].u_tof/active_q_reg[3]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/active_q[4]/q u_sens/G_SENS[1].u_tof/active_q_reg[4]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/active_q[5]/q u_sens/G_SENS[1].u_tof/active_q_reg[5]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/active_q[6]/q u_sens/G_SENS[1].u_tof/active_q_reg[6]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/active_q[7]/q u_sens/G_SENS[1].u_tof/active_q_reg[7]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/alloc_ptr_q[0]/q u_sens/G_SENS[1].u_tof/alloc_ptr_q_reg[0]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/alloc_ptr_q[1]/q u_sens/G_SENS[1].u_tof/alloc_ptr_q_reg[1]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/alloc_ptr_q[2]/q u_sens/G_SENS[1].u_tof/alloc_ptr_q_reg[2]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/cnt_q[0][0]/q u_sens/G_SENS[1].u_tof/cnt_q_reg[0][0]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/cnt_q[0][1]/q u_sens/G_SENS[1].u_tof/cnt_q_reg[0][1]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/cnt_q[0][2]/q u_sens/G_SENS[1].u_tof/cnt_q_reg[0][2]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/cnt_q[0][3]/q u_sens/G_SENS[1].u_tof/cnt_q_reg[0][3]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/cnt_q[0][4]/q u_sens/G_SENS[1].u_tof/cnt_q_reg[0][4]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/cnt_q[0][5]/q u_sens/G_SENS[1].u_tof/cnt_q_reg[0][5]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/cnt_q[1][0]/q u_sens/G_SENS[1].u_tof/cnt_q_reg[1][0]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/cnt_q[1][1]/q u_sens/G_SENS[1].u_tof/cnt_q_reg[1][1]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/cnt_q[1][2]/q u_sens/G_SENS[1].u_tof/cnt_q_reg[1][2]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/cnt_q[1][3]/q u_sens/G_SENS[1].u_tof/cnt_q_reg[1][3]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/cnt_q[1][4]/q u_sens/G_SENS[1].u_tof/cnt_q_reg[1][4]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/cnt_q[1][5]/q u_sens/G_SENS[1].u_tof/cnt_q_reg[1][5]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/cnt_q[2][0]/q u_sens/G_SENS[1].u_tof/cnt_q_reg[2][0]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/cnt_q[2][1]/q u_sens/G_SENS[1].u_tof/cnt_q_reg[2][1]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/cnt_q[2][2]/q u_sens/G_SENS[1].u_tof/cnt_q_reg[2][2]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/cnt_q[2][3]/q u_sens/G_SENS[1].u_tof/cnt_q_reg[2][3]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/cnt_q[2][4]/q u_sens/G_SENS[1].u_tof/cnt_q_reg[2][4]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/cnt_q[2][5]/q u_sens/G_SENS[1].u_tof/cnt_q_reg[2][5]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/cnt_q[3][0]/q u_sens/G_SENS[1].u_tof/cnt_q_reg[3][0]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/cnt_q[3][1]/q u_sens/G_SENS[1].u_tof/cnt_q_reg[3][1]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/cnt_q[3][2]/q u_sens/G_SENS[1].u_tof/cnt_q_reg[3][2]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/cnt_q[3][3]/q u_sens/G_SENS[1].u_tof/cnt_q_reg[3][3]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/cnt_q[3][4]/q u_sens/G_SENS[1].u_tof/cnt_q_reg[3][4]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/cnt_q[3][5]/q u_sens/G_SENS[1].u_tof/cnt_q_reg[3][5]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/cnt_q[4][0]/q u_sens/G_SENS[1].u_tof/cnt_q_reg[4][0]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/cnt_q[4][1]/q u_sens/G_SENS[1].u_tof/cnt_q_reg[4][1]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/cnt_q[4][2]/q u_sens/G_SENS[1].u_tof/cnt_q_reg[4][2]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/cnt_q[4][3]/q u_sens/G_SENS[1].u_tof/cnt_q_reg[4][3]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/cnt_q[4][4]/q u_sens/G_SENS[1].u_tof/cnt_q_reg[4][4]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/cnt_q[4][5]/q u_sens/G_SENS[1].u_tof/cnt_q_reg[4][5]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/cnt_q[5][0]/q u_sens/G_SENS[1].u_tof/cnt_q_reg[5][0]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/cnt_q[5][1]/q u_sens/G_SENS[1].u_tof/cnt_q_reg[5][1]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/cnt_q[5][2]/q u_sens/G_SENS[1].u_tof/cnt_q_reg[5][2]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/cnt_q[5][3]/q u_sens/G_SENS[1].u_tof/cnt_q_reg[5][3]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/cnt_q[5][4]/q u_sens/G_SENS[1].u_tof/cnt_q_reg[5][4]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/cnt_q[5][5]/q u_sens/G_SENS[1].u_tof/cnt_q_reg[5][5]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/cnt_q[6][0]/q u_sens/G_SENS[1].u_tof/cnt_q_reg[6][0]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/cnt_q[6][1]/q u_sens/G_SENS[1].u_tof/cnt_q_reg[6][1]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/cnt_q[6][2]/q u_sens/G_SENS[1].u_tof/cnt_q_reg[6][2]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/cnt_q[6][3]/q u_sens/G_SENS[1].u_tof/cnt_q_reg[6][3]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/cnt_q[6][4]/q u_sens/G_SENS[1].u_tof/cnt_q_reg[6][4]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/cnt_q[6][5]/q u_sens/G_SENS[1].u_tof/cnt_q_reg[6][5]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/cnt_q[7][0]/q u_sens/G_SENS[1].u_tof/cnt_q_reg[7][0]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/cnt_q[7][1]/q u_sens/G_SENS[1].u_tof/cnt_q_reg[7][1]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/cnt_q[7][2]/q u_sens/G_SENS[1].u_tof/cnt_q_reg[7][2]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/cnt_q[7][3]/q u_sens/G_SENS[1].u_tof/cnt_q_reg[7][3]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/cnt_q[7][4]/q u_sens/G_SENS[1].u_tof/cnt_q_reg[7][4]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/cnt_q[7][5]/q u_sens/G_SENS[1].u_tof/cnt_q_reg[7][5]/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].u_tof/out_pulse/q u_sens/G_SENS[1].u_tof/out_pulse_reg/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/active_q[0]/q u_sens/G_SENS[2].u_tof/active_q_reg[0]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/active_q[1]/q u_sens/G_SENS[2].u_tof/active_q_reg[1]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/active_q[2]/q u_sens/G_SENS[2].u_tof/active_q_reg[2]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/active_q[3]/q u_sens/G_SENS[2].u_tof/active_q_reg[3]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/active_q[4]/q u_sens/G_SENS[2].u_tof/active_q_reg[4]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/active_q[5]/q u_sens/G_SENS[2].u_tof/active_q_reg[5]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/active_q[6]/q u_sens/G_SENS[2].u_tof/active_q_reg[6]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/active_q[7]/q u_sens/G_SENS[2].u_tof/active_q_reg[7]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/alloc_ptr_q[0]/q u_sens/G_SENS[2].u_tof/alloc_ptr_q_reg[0]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/alloc_ptr_q[1]/q u_sens/G_SENS[2].u_tof/alloc_ptr_q_reg[1]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/alloc_ptr_q[2]/q u_sens/G_SENS[2].u_tof/alloc_ptr_q_reg[2]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/cnt_q[0][0]/q u_sens/G_SENS[2].u_tof/cnt_q_reg[0][0]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/cnt_q[0][1]/q u_sens/G_SENS[2].u_tof/cnt_q_reg[0][1]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/cnt_q[0][2]/q u_sens/G_SENS[2].u_tof/cnt_q_reg[0][2]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/cnt_q[0][3]/q u_sens/G_SENS[2].u_tof/cnt_q_reg[0][3]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/cnt_q[0][4]/q u_sens/G_SENS[2].u_tof/cnt_q_reg[0][4]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/cnt_q[0][5]/q u_sens/G_SENS[2].u_tof/cnt_q_reg[0][5]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/cnt_q[1][0]/q u_sens/G_SENS[2].u_tof/cnt_q_reg[1][0]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/cnt_q[1][1]/q u_sens/G_SENS[2].u_tof/cnt_q_reg[1][1]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/cnt_q[1][2]/q u_sens/G_SENS[2].u_tof/cnt_q_reg[1][2]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/cnt_q[1][3]/q u_sens/G_SENS[2].u_tof/cnt_q_reg[1][3]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/cnt_q[1][4]/q u_sens/G_SENS[2].u_tof/cnt_q_reg[1][4]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/cnt_q[1][5]/q u_sens/G_SENS[2].u_tof/cnt_q_reg[1][5]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/cnt_q[2][0]/q u_sens/G_SENS[2].u_tof/cnt_q_reg[2][0]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/cnt_q[2][1]/q u_sens/G_SENS[2].u_tof/cnt_q_reg[2][1]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/cnt_q[2][2]/q u_sens/G_SENS[2].u_tof/cnt_q_reg[2][2]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/cnt_q[2][3]/q u_sens/G_SENS[2].u_tof/cnt_q_reg[2][3]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/cnt_q[2][4]/q u_sens/G_SENS[2].u_tof/cnt_q_reg[2][4]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/cnt_q[2][5]/q u_sens/G_SENS[2].u_tof/cnt_q_reg[2][5]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/cnt_q[3][0]/q u_sens/G_SENS[2].u_tof/cnt_q_reg[3][0]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/cnt_q[3][1]/q u_sens/G_SENS[2].u_tof/cnt_q_reg[3][1]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/cnt_q[3][2]/q u_sens/G_SENS[2].u_tof/cnt_q_reg[3][2]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/cnt_q[3][3]/q u_sens/G_SENS[2].u_tof/cnt_q_reg[3][3]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/cnt_q[3][4]/q u_sens/G_SENS[2].u_tof/cnt_q_reg[3][4]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/cnt_q[3][5]/q u_sens/G_SENS[2].u_tof/cnt_q_reg[3][5]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/cnt_q[4][0]/q u_sens/G_SENS[2].u_tof/cnt_q_reg[4][0]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/cnt_q[4][1]/q u_sens/G_SENS[2].u_tof/cnt_q_reg[4][1]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/cnt_q[4][2]/q u_sens/G_SENS[2].u_tof/cnt_q_reg[4][2]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/cnt_q[4][3]/q u_sens/G_SENS[2].u_tof/cnt_q_reg[4][3]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/cnt_q[4][4]/q u_sens/G_SENS[2].u_tof/cnt_q_reg[4][4]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/cnt_q[4][5]/q u_sens/G_SENS[2].u_tof/cnt_q_reg[4][5]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/cnt_q[5][0]/q u_sens/G_SENS[2].u_tof/cnt_q_reg[5][0]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/cnt_q[5][1]/q u_sens/G_SENS[2].u_tof/cnt_q_reg[5][1]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/cnt_q[5][2]/q u_sens/G_SENS[2].u_tof/cnt_q_reg[5][2]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/cnt_q[5][3]/q u_sens/G_SENS[2].u_tof/cnt_q_reg[5][3]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/cnt_q[5][4]/q u_sens/G_SENS[2].u_tof/cnt_q_reg[5][4]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/cnt_q[5][5]/q u_sens/G_SENS[2].u_tof/cnt_q_reg[5][5]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/cnt_q[6][0]/q u_sens/G_SENS[2].u_tof/cnt_q_reg[6][0]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/cnt_q[6][1]/q u_sens/G_SENS[2].u_tof/cnt_q_reg[6][1]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/cnt_q[6][2]/q u_sens/G_SENS[2].u_tof/cnt_q_reg[6][2]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/cnt_q[6][3]/q u_sens/G_SENS[2].u_tof/cnt_q_reg[6][3]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/cnt_q[6][4]/q u_sens/G_SENS[2].u_tof/cnt_q_reg[6][4]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/cnt_q[6][5]/q u_sens/G_SENS[2].u_tof/cnt_q_reg[6][5]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/cnt_q[7][0]/q u_sens/G_SENS[2].u_tof/cnt_q_reg[7][0]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/cnt_q[7][1]/q u_sens/G_SENS[2].u_tof/cnt_q_reg[7][1]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/cnt_q[7][2]/q u_sens/G_SENS[2].u_tof/cnt_q_reg[7][2]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/cnt_q[7][3]/q u_sens/G_SENS[2].u_tof/cnt_q_reg[7][3]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/cnt_q[7][4]/q u_sens/G_SENS[2].u_tof/cnt_q_reg[7][4]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/cnt_q[7][5]/q u_sens/G_SENS[2].u_tof/cnt_q_reg[7][5]/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].u_tof/out_pulse/q u_sens/G_SENS[2].u_tof/out_pulse_reg/Q -type DFF DFF
add mapped point u_sens/ux/r[31]/q u_sens/ux/r_reg[31]/Q -type DFF DFF
add mapped point u_sens/ux/r[30]/q u_sens/ux/r_reg[30]/Q -type DFF DFF
add mapped point u_sens/ux/r[29]/q u_sens/ux/r_reg[29]/Q -type DFF DFF
add mapped point u_sens/ux/r[28]/q u_sens/ux/r_reg[28]/Q -type DFF DFF
add mapped point u_sens/ux/r[27]/q u_sens/ux/r_reg[27]/Q -type DFF DFF
add mapped point u_sens/ux/r[26]/q u_sens/ux/r_reg[26]/Q -type DFF DFF
add mapped point u_sens/ux/r[25]/q u_sens/ux/r_reg[25]/Q -type DFF DFF
add mapped point u_sens/ux/r[24]/q u_sens/ux/r_reg[24]/Q -type DFF DFF
add mapped point u_sens/ux/r[23]/q u_sens/ux/r_reg[23]/Q -type DFF DFF
add mapped point u_sens/ux/r[22]/q u_sens/ux/r_reg[22]/Q -type DFF DFF
add mapped point u_sens/ux/r[21]/q u_sens/ux/r_reg[21]/Q -type DFF DFF
add mapped point u_sens/ux/r[20]/q u_sens/ux/r_reg[20]/Q -type DFF DFF
add mapped point u_sens/ux/r[19]/q u_sens/ux/r_reg[19]/Q -type DFF DFF
add mapped point u_sens/ux/r[18]/q u_sens/ux/r_reg[18]/Q -type DFF DFF
add mapped point u_sens/ux/r[17]/q u_sens/ux/r_reg[17]/Q -type DFF DFF
add mapped point u_sens/ux/r[16]/q u_sens/ux/r_reg[16]/Q -type DFF DFF
add mapped point u_sens/ux/r[15]/q u_sens/ux/r_reg[15]/Q -type DFF DFF
add mapped point u_sens/ux/r[14]/q u_sens/ux/r_reg[14]/Q -type DFF DFF
add mapped point u_sens/ux/r[13]/q u_sens/ux/r_reg[13]/Q -type DFF DFF
add mapped point u_sens/ux/r[12]/q u_sens/ux/r_reg[12]/Q -type DFF DFF
add mapped point u_sens/ux/r[11]/q u_sens/ux/r_reg[11]/Q -type DFF DFF
add mapped point u_sens/ux/r[10]/q u_sens/ux/r_reg[10]/Q -type DFF DFF
add mapped point u_sens/ux/r[9]/q u_sens/ux/r_reg[9]/Q -type DFF DFF
add mapped point u_sens/ux/r[8]/q u_sens/ux/r_reg[8]/Q -type DFF DFF
add mapped point u_sens/ux/r[7]/q u_sens/ux/r_reg[7]/Q -type DFF DFF
add mapped point u_sens/ux/r[6]/q u_sens/ux/r_reg[6]/Q -type DFF DFF
add mapped point u_sens/ux/r[5]/q u_sens/ux/r_reg[5]/Q -type DFF DFF
add mapped point u_sens/ux/r[4]/q u_sens/ux/r_reg[4]/Q -type DFF DFF
add mapped point u_sens/ux/r[3]/q u_sens/ux/r_reg[3]/Q -type DFF DFF
add mapped point u_sens/ux/r[2]/q u_sens/ux/r_reg[2]/Q -type DFF DFF
add mapped point u_sens/ux/r[1]/q u_sens/ux/r_reg[1]/Q -type DFF DFF
add mapped point u_sens/ux/r[0]/q u_sens/ux/r_reg[0]/Q -type DFF DFF
add mapped point u_sens/uy/r[31]/q u_sens/uy/r_reg[31]/Q -type DFF DFF
add mapped point u_sens/uy/r[30]/q u_sens/uy/r_reg[30]/Q -type DFF DFF
add mapped point u_sens/uy/r[29]/q u_sens/uy/r_reg[29]/Q -type DFF DFF
add mapped point u_sens/uy/r[28]/q u_sens/uy/r_reg[28]/Q -type DFF DFF
add mapped point u_sens/uy/r[27]/q u_sens/uy/r_reg[27]/Q -type DFF DFF
add mapped point u_sens/uy/r[26]/q u_sens/uy/r_reg[26]/Q -type DFF DFF
add mapped point u_sens/uy/r[25]/q u_sens/uy/r_reg[25]/Q -type DFF DFF
add mapped point u_sens/uy/r[24]/q u_sens/uy/r_reg[24]/Q -type DFF DFF
add mapped point u_sens/uy/r[23]/q u_sens/uy/r_reg[23]/Q -type DFF DFF
add mapped point u_sens/uy/r[22]/q u_sens/uy/r_reg[22]/Q -type DFF DFF
add mapped point u_sens/uy/r[21]/q u_sens/uy/r_reg[21]/Q -type DFF DFF
add mapped point u_sens/uy/r[20]/q u_sens/uy/r_reg[20]/Q -type DFF DFF
add mapped point u_sens/uy/r[19]/q u_sens/uy/r_reg[19]/Q -type DFF DFF
add mapped point u_sens/uy/r[18]/q u_sens/uy/r_reg[18]/Q -type DFF DFF
add mapped point u_sens/uy/r[17]/q u_sens/uy/r_reg[17]/Q -type DFF DFF
add mapped point u_sens/uy/r[16]/q u_sens/uy/r_reg[16]/Q -type DFF DFF
add mapped point u_sens/uy/r[15]/q u_sens/uy/r_reg[15]/Q -type DFF DFF
add mapped point u_sens/uy/r[14]/q u_sens/uy/r_reg[14]/Q -type DFF DFF
add mapped point u_sens/uy/r[13]/q u_sens/uy/r_reg[13]/Q -type DFF DFF
add mapped point u_sens/uy/r[12]/q u_sens/uy/r_reg[12]/Q -type DFF DFF
add mapped point u_sens/uy/r[11]/q u_sens/uy/r_reg[11]/Q -type DFF DFF
add mapped point u_sens/uy/r[10]/q u_sens/uy/r_reg[10]/Q -type DFF DFF
add mapped point u_sens/uy/r[9]/q u_sens/uy/r_reg[9]/Q -type DFF DFF
add mapped point u_sens/uy/r[8]/q u_sens/uy/r_reg[8]/Q -type DFF DFF
add mapped point u_sens/uy/r[7]/q u_sens/uy/r_reg[7]/Q -type DFF DFF
add mapped point u_sens/uy/r[6]/q u_sens/uy/r_reg[6]/Q -type DFF DFF
add mapped point u_sens/uy/r[5]/q u_sens/uy/r_reg[5]/Q -type DFF DFF
add mapped point u_sens/uy/r[4]/q u_sens/uy/r_reg[4]/Q -type DFF DFF
add mapped point u_sens/uy/r[3]/q u_sens/uy/r_reg[3]/Q -type DFF DFF
add mapped point u_sens/uy/r[2]/q u_sens/uy/r_reg[2]/Q -type DFF DFF
add mapped point u_sens/uy/r[1]/q u_sens/uy/r_reg[1]/Q -type DFF DFF
add mapped point u_sens/uy/r[0]/q u_sens/uy/r_reg[0]/Q -type DFF DFF
add mapped point u_sens/G_SENS[0].spike_raw/q u_sens/G_SENS[0].spike_raw_reg/Q -type DFF DFF
add mapped point u_sens/G_SENS[1].spike_raw/q u_sens/G_SENS[1].spike_raw_reg/Q -type DFF DFF
add mapped point u_sens/G_SENS[2].spike_raw/q u_sens/G_SENS[2].spike_raw_reg/Q -type DFF DFF
add mapped point u_sens/dist_bin[0][0]/q u_sens/dist_bin_reg[0][0]/Q -type DFF DFF
add mapped point u_sens/dist_bin[0][1]/q u_sens/dist_bin_reg[0][1]/Q -type DFF DFF
add mapped point u_sens/dist_bin[0][2]/q u_sens/dist_bin_reg[0][2]/Q -type DFF DFF
add mapped point u_sens/dist_bin[0][3]/q u_sens/dist_bin_reg[0][3]/Q -type DFF DFF
add mapped point u_sens/dist_bin[0][4]/q u_sens/dist_bin_reg[0][4]/Q -type DFF DFF
add mapped point u_sens/dist_bin[1][0]/q u_sens/dist_bin_reg[1][0]/Q -type DFF DFF
add mapped point u_sens/dist_bin[1][1]/q u_sens/dist_bin_reg[1][1]/Q -type DFF DFF
add mapped point u_sens/dist_bin[1][2]/q u_sens/dist_bin_reg[1][2]/Q -type DFF DFF
add mapped point u_sens/dist_bin[1][3]/q u_sens/dist_bin_reg[1][3]/Q -type DFF DFF
add mapped point u_sens/dist_bin[1][4]/q u_sens/dist_bin_reg[1][4]/Q -type DFF DFF
add mapped point u_sens/dist_bin[2][0]/q u_sens/dist_bin_reg[2][0]/Q -type DFF DFF
add mapped point u_sens/dist_bin[2][1]/q u_sens/dist_bin_reg[2][1]/Q -type DFF DFF
add mapped point u_sens/dist_bin[2][2]/q u_sens/dist_bin_reg[2][2]/Q -type DFF DFF
add mapped point u_sens/dist_bin[2][3]/q u_sens/dist_bin_reg[2][3]/Q -type DFF DFF
add mapped point u_sens/dist_bin[2][4]/q u_sens/dist_bin_reg[2][4]/Q -type DFF DFF
add mapped point u_sens/rate_bin[0][0]/q u_sens/rate_bin_reg[0][0]/Q -type DFF DFF
add mapped point u_sens/rate_bin[0][1]/q u_sens/rate_bin_reg[0][1]/Q -type DFF DFF
add mapped point u_sens/rate_bin[0][2]/q u_sens/rate_bin_reg[0][2]/Q -type DFF DFF
add mapped point u_sens/rate_bin[0][3]/q u_sens/rate_bin_reg[0][3]/Q -type DFF DFF
add mapped point u_sens/rate_bin[0][4]/q u_sens/rate_bin_reg[0][4]/Q -type DFF DFF
add mapped point u_sens/rate_bin[0][5]/q u_sens/rate_bin_reg[0][5]/Q -type DFF DFF
add mapped point u_sens/rate_bin[0][6]/q u_sens/rate_bin_reg[0][6]/Q -type DFF DFF
add mapped point u_sens/rate_bin[1][0]/q u_sens/rate_bin_reg[1][0]/Q -type DFF DFF
add mapped point u_sens/rate_bin[1][1]/q u_sens/rate_bin_reg[1][1]/Q -type DFF DFF
add mapped point u_sens/rate_bin[1][2]/q u_sens/rate_bin_reg[1][2]/Q -type DFF DFF
add mapped point u_sens/rate_bin[1][3]/q u_sens/rate_bin_reg[1][3]/Q -type DFF DFF
add mapped point u_sens/rate_bin[1][4]/q u_sens/rate_bin_reg[1][4]/Q -type DFF DFF
add mapped point u_sens/rate_bin[1][5]/q u_sens/rate_bin_reg[1][5]/Q -type DFF DFF
add mapped point u_sens/rate_bin[1][6]/q u_sens/rate_bin_reg[1][6]/Q -type DFF DFF
add mapped point u_sens/rate_bin[2][0]/q u_sens/rate_bin_reg[2][0]/Q -type DFF DFF
add mapped point u_sens/rate_bin[2][1]/q u_sens/rate_bin_reg[2][1]/Q -type DFF DFF
add mapped point u_sens/rate_bin[2][2]/q u_sens/rate_bin_reg[2][2]/Q -type DFF DFF
add mapped point u_sens/rate_bin[2][3]/q u_sens/rate_bin_reg[2][3]/Q -type DFF DFF
add mapped point u_sens/rate_bin[2][4]/q u_sens/rate_bin_reg[2][4]/Q -type DFF DFF
add mapped point u_sens/rate_bin[2][5]/q u_sens/rate_bin_reg[2][5]/Q -type DFF DFF
add mapped point u_sens/rate_bin[2][6]/q u_sens/rate_bin_reg[2][6]/Q -type DFF DFF
add mapped point ev_valid/q ev_valid_reg/Q -type DFF DFF
add mapped point pre_id[1]/q pre_id_reg[1]/Q -type DFF DFF
add mapped point pre_id[0]/q pre_id_reg[0]/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
