
// Generated by Cadence Genus(TM) Synthesis Solution 23.14-s090_1
// Generated on: Nov  2 2025 19:11:17 KST (Nov  2 2025 10:11:17 UTC)

// Verification Directory fv/ai_neuron_top_comp_v2 

module g_pulse_accumulator_W24(clk, rst_n, clk_en, plus_pulse_i,
     minus_pulse_i, value_o);
  input clk, rst_n, clk_en, plus_pulse_i, minus_pulse_i;
  output [23:0] value_o;
  wire clk, rst_n, clk_en, plus_pulse_i, minus_pulse_i;
  wire [23:0] value_o;
  assign value_o[0] = 1'b0;
  assign value_o[1] = 1'b0;
  assign value_o[2] = 1'b0;
  assign value_o[3] = 1'b0;
  assign value_o[4] = 1'b0;
  assign value_o[5] = 1'b0;
  assign value_o[6] = 1'b0;
  assign value_o[7] = 1'b0;
  assign value_o[8] = 1'b0;
  assign value_o[9] = 1'b0;
  assign value_o[10] = 1'b0;
  assign value_o[11] = 1'b0;
  assign value_o[12] = 1'b0;
  assign value_o[13] = 1'b0;
  assign value_o[14] = 1'b0;
  assign value_o[15] = 1'b0;
  assign value_o[16] = 1'b0;
  assign value_o[17] = 1'b0;
  assign value_o[18] = 1'b0;
  assign value_o[19] = 1'b0;
  assign value_o[20] = 1'b0;
  assign value_o[21] = 1'b0;
  assign value_o[22] = 1'b0;
  assign value_o[23] = 1'b0;
endmodule

module g_pulse_accumulator_W24_442(clk, rst_n, clk_en, plus_pulse_i,
     minus_pulse_i, value_o);
  input clk, rst_n, clk_en, plus_pulse_i, minus_pulse_i;
  output [23:0] value_o;
  wire clk, rst_n, clk_en, plus_pulse_i, minus_pulse_i;
  wire [23:0] value_o;
  assign value_o[0] = 1'b0;
  assign value_o[1] = 1'b0;
  assign value_o[2] = 1'b0;
  assign value_o[3] = 1'b0;
  assign value_o[4] = 1'b0;
  assign value_o[5] = 1'b0;
  assign value_o[6] = 1'b0;
  assign value_o[7] = 1'b0;
  assign value_o[8] = 1'b0;
  assign value_o[9] = 1'b0;
  assign value_o[10] = 1'b0;
  assign value_o[11] = 1'b0;
  assign value_o[12] = 1'b0;
  assign value_o[13] = 1'b0;
  assign value_o[14] = 1'b0;
  assign value_o[15] = 1'b0;
  assign value_o[16] = 1'b0;
  assign value_o[17] = 1'b0;
  assign value_o[18] = 1'b0;
  assign value_o[19] = 1'b0;
  assign value_o[20] = 1'b0;
  assign value_o[21] = 1'b0;
  assign value_o[22] = 1'b0;
  assign value_o[23] = 1'b0;
endmodule

module
     weight_ram_adjlist_N_NEURON64_NEURON_ID_W6_TOTAL_SYNAPSES4096_SYN_ADDR_W16_DEG_W12_WEIGHT_W16(clk,
     rst_n, clk_en, req_valid, req_ready, req_src_id, out_valid,
     out_ready, out_dst_id, out_weight, out_addr, out_last,
     upd_valid_i, upd_ready_o, upd_addr_i, upd_dw_i);
  input clk, rst_n, clk_en, req_valid, out_ready, upd_valid_i;
  input [5:0] req_src_id;
  input [15:0] upd_addr_i, upd_dw_i;
  output req_ready, out_valid, out_last, upd_ready_o;
  output [5:0] out_dst_id;
  output [15:0] out_weight, out_addr;
  wire clk, rst_n, clk_en, req_valid, out_ready, upd_valid_i;
  wire [5:0] req_src_id;
  wire [15:0] upd_addr_i, upd_dw_i;
  wire req_ready, out_valid, out_last, upd_ready_o;
  wire [5:0] out_dst_id;
  wire [15:0] out_weight, out_addr;
  assign upd_ready_o = 1'b1;
  assign out_last = 1'b0;
  assign out_addr[0] = 1'b0;
  assign out_addr[1] = 1'b0;
  assign out_addr[2] = 1'b0;
  assign out_addr[3] = 1'b0;
  assign out_addr[4] = 1'b0;
  assign out_addr[5] = 1'b0;
  assign out_addr[6] = 1'b0;
  assign out_addr[7] = 1'b0;
  assign out_addr[8] = 1'b0;
  assign out_addr[9] = 1'b0;
  assign out_addr[10] = 1'b0;
  assign out_addr[11] = 1'b0;
  assign out_addr[12] = 1'b0;
  assign out_addr[13] = 1'b0;
  assign out_addr[14] = 1'b0;
  assign out_addr[15] = 1'b0;
  assign out_weight[0] = 1'b0;
  assign out_weight[1] = 1'b0;
  assign out_weight[2] = 1'b0;
  assign out_weight[3] = 1'b0;
  assign out_weight[4] = 1'b0;
  assign out_weight[5] = 1'b0;
  assign out_weight[6] = 1'b0;
  assign out_weight[7] = 1'b0;
  assign out_weight[8] = 1'b0;
  assign out_weight[9] = 1'b0;
  assign out_weight[10] = 1'b0;
  assign out_weight[11] = 1'b0;
  assign out_weight[12] = 1'b0;
  assign out_weight[13] = 1'b0;
  assign out_weight[14] = 1'b0;
  assign out_weight[15] = 1'b0;
  assign out_dst_id[0] = 1'b0;
  assign out_dst_id[1] = 1'b0;
  assign out_dst_id[2] = 1'b1;
  assign out_dst_id[3] = 1'b1;
  assign out_dst_id[4] = 1'b1;
  assign out_dst_id[5] = 1'b1;
  assign out_valid = 1'b0;
  assign req_ready = 1'b0;
endmodule

module
     dynamic_synapse_processor_stream_v2_N_NEURON64_NEURON_ID_W6_WEIGHT_W16_ACC_W24_GRID_W128_GRID_H128_TOTAL_SYNAPSES4096_SYN_ADDR_W16_DEG_W12(clk,
     rst_n, clk_en, ev_valid, ev_ready, pre_id_i, pos_x_i, pos_y_i,
     mass_u8_i, syn_out_valid, syn_out_ready, syn_dst_id_o,
     syn_weight_o, syn_addr_o, syn_pre_id_o, upd_valid_i, upd_ready_o,
     upd_addr_i, upd_dw_i);
  input clk, rst_n, clk_en, ev_valid, syn_out_ready, upd_valid_i;
  input [5:0] pre_id_i;
  input [15:0] pos_x_i, pos_y_i, upd_addr_i, upd_dw_i;
  input [7:0] mass_u8_i;
  output ev_ready, syn_out_valid, upd_ready_o;
  output [5:0] syn_dst_id_o, syn_pre_id_o;
  output [15:0] syn_weight_o, syn_addr_o;
  wire clk, rst_n, clk_en, ev_valid, syn_out_ready, upd_valid_i;
  wire [5:0] pre_id_i;
  wire [15:0] pos_x_i, pos_y_i, upd_addr_i, upd_dw_i;
  wire [7:0] mass_u8_i;
  wire ev_ready, syn_out_valid, upd_ready_o;
  wire [5:0] syn_dst_id_o, syn_pre_id_o;
  wire [15:0] syn_weight_o, syn_addr_o;
  wire [5:0] ram_dst_id;
  wire [15:0] ram_weight;
  wire [15:0] ram_addr;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, n_2, out_last_int, ram_out_valid;
  assign upd_ready_o = 1'b0;
  assign syn_pre_id_o[0] = 1'b0;
  assign syn_pre_id_o[1] = 1'b0;
  assign syn_pre_id_o[2] = 1'b0;
  assign syn_pre_id_o[3] = 1'b0;
  assign syn_pre_id_o[4] = 1'b0;
  assign syn_pre_id_o[5] = 1'b0;
  assign syn_addr_o[0] = 1'b0;
  assign syn_addr_o[1] = 1'b0;
  assign syn_addr_o[2] = 1'b0;
  assign syn_addr_o[3] = 1'b0;
  assign syn_addr_o[4] = 1'b0;
  assign syn_addr_o[5] = 1'b0;
  assign syn_addr_o[6] = 1'b0;
  assign syn_addr_o[7] = 1'b0;
  assign syn_addr_o[8] = 1'b0;
  assign syn_addr_o[9] = 1'b0;
  assign syn_addr_o[10] = 1'b0;
  assign syn_addr_o[11] = 1'b0;
  assign syn_addr_o[12] = 1'b0;
  assign syn_addr_o[13] = 1'b0;
  assign syn_addr_o[14] = 1'b0;
  assign syn_addr_o[15] = 1'b0;
  assign syn_weight_o[0] = 1'b0;
  assign syn_weight_o[1] = 1'b0;
  assign syn_weight_o[2] = 1'b0;
  assign syn_weight_o[3] = 1'b0;
  assign syn_weight_o[4] = 1'b0;
  assign syn_weight_o[5] = 1'b0;
  assign syn_weight_o[6] = 1'b0;
  assign syn_weight_o[7] = 1'b0;
  assign syn_weight_o[8] = 1'b0;
  assign syn_weight_o[9] = 1'b0;
  assign syn_weight_o[10] = 1'b0;
  assign syn_weight_o[11] = 1'b0;
  assign syn_weight_o[12] = 1'b0;
  assign syn_weight_o[13] = 1'b0;
  assign syn_weight_o[14] = 1'b0;
  assign syn_weight_o[15] = 1'b0;
  assign syn_dst_id_o[0] = 1'b0;
  assign syn_dst_id_o[1] = 1'b0;
  assign syn_dst_id_o[2] = 1'b1;
  assign syn_dst_id_o[3] = 1'b1;
  assign syn_dst_id_o[4] = 1'b1;
  assign syn_dst_id_o[5] = 1'b1;
  assign syn_out_valid = 1'b0;
  assign ev_ready = 1'b0;
  weight_ram_adjlist_N_NEURON64_NEURON_ID_W6_TOTAL_SYNAPSES4096_SYN_ADDR_W16_DEG_W12_WEIGHT_W16
       u_adj(.clk (1'b0), .rst_n (rst_n), .clk_en (1'b0), .req_valid
       (1'b0), .req_ready (UNCONNECTED), .req_src_id (6'b0), .out_valid
       (ram_out_valid), .out_ready (1'b1), .out_dst_id ({UNCONNECTED3,
       UNCONNECTED2, UNCONNECTED1, UNCONNECTED0, ram_dst_id[1:0]}),
       .out_weight (ram_weight), .out_addr (ram_addr), .out_last
       (out_last_int), .upd_valid_i (1'b0), .upd_ready_o (n_2),
       .upd_addr_i (16'b0), .upd_dw_i (16'b0));
endmodule

module motor_decoder_4dir(clk, rst_n, clk_en, ch_fire_i, north_o,
     south_o, east_o, west_o);
  input clk, rst_n, clk_en;
  input [3:0] ch_fire_i;
  output north_o, south_o, east_o, west_o;
  wire clk, rst_n, clk_en;
  wire [3:0] ch_fire_i;
  wire north_o, south_o, east_o, west_o;
  assign west_o = 1'b0;
  assign east_o = 1'b0;
  assign south_o = 1'b0;
  assign north_o = 1'b0;
endmodule

module lfsr32(clk, rst_n, q);
  input clk, rst_n;
  output [31:0] q;
  wire clk, rst_n;
  wire [31:0] q;
  assign q[0] = 1'b0;
  assign q[1] = 1'b0;
  assign q[2] = 1'b0;
  assign q[3] = 1'b0;
  assign q[4] = 1'b0;
  assign q[5] = 1'b0;
  assign q[6] = 1'b0;
  assign q[7] = 1'b0;
  assign q[8] = 1'b0;
  assign q[9] = 1'b0;
  assign q[10] = 1'b0;
  assign q[11] = 1'b0;
  assign q[12] = 1'b0;
  assign q[13] = 1'b0;
  assign q[14] = 1'b0;
  assign q[15] = 1'b0;
  assign q[16] = 1'b0;
  assign q[17] = 1'b0;
  assign q[18] = 1'b0;
  assign q[19] = 1'b0;
  assign q[20] = 1'b0;
  assign q[21] = 1'b0;
  assign q[22] = 1'b0;
  assign q[23] = 1'b0;
  assign q[24] = 1'b0;
  assign q[25] = 1'b0;
  assign q[26] = 1'b0;
  assign q[27] = 1'b0;
  assign q[28] = 1'b0;
  assign q[29] = 1'b0;
  assign q[30] = 1'b0;
  assign q[31] = 1'b0;
endmodule

module lfsr32_2271(clk, rst_n, q);
  input clk, rst_n;
  output [31:0] q;
  wire clk, rst_n;
  wire [31:0] q;
  assign q[0] = 1'b0;
  assign q[1] = 1'b0;
  assign q[2] = 1'b0;
  assign q[3] = 1'b0;
  assign q[4] = 1'b0;
  assign q[5] = 1'b0;
  assign q[6] = 1'b0;
  assign q[7] = 1'b0;
  assign q[8] = 1'b0;
  assign q[9] = 1'b0;
  assign q[10] = 1'b0;
  assign q[11] = 1'b0;
  assign q[12] = 1'b0;
  assign q[13] = 1'b0;
  assign q[14] = 1'b0;
  assign q[15] = 1'b0;
  assign q[16] = 1'b0;
  assign q[17] = 1'b0;
  assign q[18] = 1'b0;
  assign q[19] = 1'b0;
  assign q[20] = 1'b0;
  assign q[21] = 1'b0;
  assign q[22] = 1'b0;
  assign q[23] = 1'b0;
  assign q[24] = 1'b0;
  assign q[25] = 1'b0;
  assign q[26] = 1'b0;
  assign q[27] = 1'b0;
  assign q[28] = 1'b0;
  assign q[29] = 1'b0;
  assign q[30] = 1'b0;
  assign q[31] = 1'b0;
endmodule

module physics_integrator_2d(clk, rst_n, clk_en, force_x_q, force_y_q,
     mass_g, pos_mm_x_o, pos_mm_y_o, goal_reached_o);
  input clk, rst_n, clk_en;
  input [23:0] force_x_q, force_y_q;
  input [5:0] mass_g;
  output [15:0] pos_mm_x_o, pos_mm_y_o;
  output goal_reached_o;
  wire clk, rst_n, clk_en;
  wire [23:0] force_x_q, force_y_q;
  wire [5:0] mass_g;
  wire [15:0] pos_mm_x_o, pos_mm_y_o;
  wire goal_reached_o;
  wire [31:0] rnd_x;
  wire [31:0] rnd_y;
  assign goal_reached_o = 1'b0;
  assign pos_mm_y_o[0] = 1'b0;
  assign pos_mm_y_o[1] = 1'b0;
  assign pos_mm_y_o[2] = 1'b0;
  assign pos_mm_y_o[3] = 1'b0;
  assign pos_mm_y_o[4] = 1'b0;
  assign pos_mm_y_o[5] = 1'b0;
  assign pos_mm_y_o[6] = 1'b0;
  assign pos_mm_y_o[7] = 1'b0;
  assign pos_mm_y_o[8] = 1'b0;
  assign pos_mm_y_o[9] = 1'b0;
  assign pos_mm_y_o[10] = 1'b0;
  assign pos_mm_y_o[11] = 1'b0;
  assign pos_mm_y_o[12] = 1'b0;
  assign pos_mm_y_o[13] = 1'b0;
  assign pos_mm_y_o[14] = 1'b0;
  assign pos_mm_y_o[15] = 1'b0;
  assign pos_mm_x_o[0] = 1'b0;
  assign pos_mm_x_o[1] = 1'b0;
  assign pos_mm_x_o[2] = 1'b0;
  assign pos_mm_x_o[3] = 1'b0;
  assign pos_mm_x_o[4] = 1'b0;
  assign pos_mm_x_o[5] = 1'b0;
  assign pos_mm_x_o[6] = 1'b0;
  assign pos_mm_x_o[7] = 1'b0;
  assign pos_mm_x_o[8] = 1'b0;
  assign pos_mm_x_o[9] = 1'b0;
  assign pos_mm_x_o[10] = 1'b0;
  assign pos_mm_x_o[11] = 1'b0;
  assign pos_mm_x_o[12] = 1'b0;
  assign pos_mm_x_o[13] = 1'b0;
  assign pos_mm_x_o[14] = 1'b0;
  assign pos_mm_x_o[15] = 1'b0;
  lfsr32 u_lx(.clk (1'b0), .rst_n (rst_n), .q (rnd_x));
  lfsr32_2271 u_ly(.clk (1'b0), .rst_n (rst_n), .q (rnd_y));
endmodule

module power_manager(clk, rst_n, clk_en_i, activity_i, clk_en_o);
  input clk, rst_n, clk_en_i, activity_i;
  output clk_en_o;
  wire clk, rst_n, clk_en_i, activity_i;
  wire clk_en_o;
  assign clk_en_o = 1'b0;
endmodule

module tof_delay_line_MAX_DELAY256(clk, rst_n, clk_en, in_pulse,
     delay_i, out_pulse);
  input clk, rst_n, clk_en, in_pulse;
  input [7:0] delay_i;
  output out_pulse;
  wire clk, rst_n, clk_en, in_pulse;
  wire [7:0] delay_i;
  wire out_pulse;
  assign out_pulse = 1'b0;
endmodule

module tof_delay_line_MAX_DELAY256_447(clk, rst_n, clk_en, in_pulse,
     delay_i, out_pulse);
  input clk, rst_n, clk_en, in_pulse;
  input [7:0] delay_i;
  output out_pulse;
  wire clk, rst_n, clk_en, in_pulse;
  wire [7:0] delay_i;
  wire out_pulse;
  assign out_pulse = 1'b0;
endmodule

module tof_delay_line_MAX_DELAY256_446(clk, rst_n, clk_en, in_pulse,
     delay_i, out_pulse);
  input clk, rst_n, clk_en, in_pulse;
  input [7:0] delay_i;
  output out_pulse;
  wire clk, rst_n, clk_en, in_pulse;
  wire [7:0] delay_i;
  wire out_pulse;
  assign out_pulse = 1'b0;
endmodule

module lfsr32_2270(clk, rst_n, q);
  input clk, rst_n;
  output [31:0] q;
  wire clk, rst_n;
  wire [31:0] q;
  assign q[0] = 1'b0;
  assign q[1] = 1'b0;
  assign q[2] = 1'b0;
  assign q[3] = 1'b0;
  assign q[4] = 1'b0;
  assign q[5] = 1'b0;
  assign q[6] = 1'b0;
  assign q[7] = 1'b0;
  assign q[8] = 1'b0;
  assign q[9] = 1'b0;
  assign q[10] = 1'b0;
  assign q[11] = 1'b0;
  assign q[12] = 1'b0;
  assign q[13] = 1'b0;
  assign q[14] = 1'b0;
  assign q[15] = 1'b0;
  assign q[16] = 1'b0;
  assign q[17] = 1'b0;
  assign q[18] = 1'b0;
  assign q[19] = 1'b0;
  assign q[20] = 1'b0;
  assign q[21] = 1'b0;
  assign q[22] = 1'b0;
  assign q[23] = 1'b0;
  assign q[24] = 1'b0;
  assign q[25] = 1'b0;
  assign q[26] = 1'b0;
  assign q[27] = 1'b0;
  assign q[28] = 1'b0;
  assign q[29] = 1'b0;
  assign q[30] = 1'b0;
  assign q[31] = 1'b0;
endmodule

module lfsr32_2269(clk, rst_n, q);
  input clk, rst_n;
  output [31:0] q;
  wire clk, rst_n;
  wire [31:0] q;
  assign q[0] = 1'b0;
  assign q[1] = 1'b0;
  assign q[2] = 1'b0;
  assign q[3] = 1'b0;
  assign q[4] = 1'b0;
  assign q[5] = 1'b0;
  assign q[6] = 1'b0;
  assign q[7] = 1'b0;
  assign q[8] = 1'b0;
  assign q[9] = 1'b0;
  assign q[10] = 1'b0;
  assign q[11] = 1'b0;
  assign q[12] = 1'b0;
  assign q[13] = 1'b0;
  assign q[14] = 1'b0;
  assign q[15] = 1'b0;
  assign q[16] = 1'b0;
  assign q[17] = 1'b0;
  assign q[18] = 1'b0;
  assign q[19] = 1'b0;
  assign q[20] = 1'b0;
  assign q[21] = 1'b0;
  assign q[22] = 1'b0;
  assign q[23] = 1'b0;
  assign q[24] = 1'b0;
  assign q[25] = 1'b0;
  assign q[26] = 1'b0;
  assign q[27] = 1'b0;
  assign q[28] = 1'b0;
  assign q[29] = 1'b0;
  assign q[30] = 1'b0;
  assign q[31] = 1'b0;
endmodule

module pressure_sensor_field_3ch(clk, rst_n, clk_en, reseed_i,
     pos_mm_x_i, pos_mm_y_i, mass_g_i, spike_o, \density_o[2] ,
     \density_o[1] , \density_o[0] , \dist_bin_o[2] , \dist_bin_o[1] ,
     \dist_bin_o[0] );
  input clk, rst_n, clk_en, reseed_i;
  input [15:0] pos_mm_x_i, pos_mm_y_i;
  input [5:0] mass_g_i;
  output [2:0] spike_o;
  output [7:0] \density_o[2] , \density_o[1] , \density_o[0] ,
       \dist_bin_o[2] , \dist_bin_o[1] , \dist_bin_o[0] ;
  wire clk, rst_n, clk_en, reseed_i;
  wire [15:0] pos_mm_x_i, pos_mm_y_i;
  wire [5:0] mass_g_i;
  wire [2:0] spike_o;
  wire [7:0] \density_o[2] , \density_o[1] , \density_o[0] ,
       \dist_bin_o[2] , \dist_bin_o[1] , \dist_bin_o[0] ;
  wire [31:0] rx;
  wire [31:0] ry;
  wire n_11, n_12, n_13;
  assign \dist_bin_o[0] [0] = 1'b0;
  assign \dist_bin_o[0] [1] = 1'b0;
  assign \dist_bin_o[0] [2] = 1'b0;
  assign \dist_bin_o[0] [3] = 1'b0;
  assign \dist_bin_o[0] [4] = 1'b0;
  assign \dist_bin_o[0] [5] = 1'b0;
  assign \dist_bin_o[0] [6] = 1'b0;
  assign \dist_bin_o[0] [7] = 1'b0;
  assign \dist_bin_o[1] [0] = 1'b0;
  assign \dist_bin_o[1] [1] = 1'b0;
  assign \dist_bin_o[1] [2] = 1'b0;
  assign \dist_bin_o[1] [3] = 1'b0;
  assign \dist_bin_o[1] [4] = 1'b0;
  assign \dist_bin_o[1] [5] = 1'b0;
  assign \dist_bin_o[1] [6] = 1'b0;
  assign \dist_bin_o[1] [7] = 1'b0;
  assign \dist_bin_o[2] [0] = 1'b0;
  assign \dist_bin_o[2] [1] = 1'b0;
  assign \dist_bin_o[2] [2] = 1'b0;
  assign \dist_bin_o[2] [3] = 1'b0;
  assign \dist_bin_o[2] [4] = 1'b0;
  assign \dist_bin_o[2] [5] = 1'b0;
  assign \dist_bin_o[2] [6] = 1'b0;
  assign \dist_bin_o[2] [7] = 1'b0;
  assign \density_o[0] [0] = 1'b0;
  assign \density_o[0] [1] = 1'b0;
  assign \density_o[0] [2] = 1'b0;
  assign \density_o[0] [3] = 1'b0;
  assign \density_o[0] [4] = 1'b0;
  assign \density_o[0] [5] = 1'b0;
  assign \density_o[0] [6] = 1'b0;
  assign \density_o[0] [7] = 1'b0;
  assign \density_o[1] [0] = 1'b0;
  assign \density_o[1] [1] = 1'b0;
  assign \density_o[1] [2] = 1'b0;
  assign \density_o[1] [3] = 1'b0;
  assign \density_o[1] [4] = 1'b0;
  assign \density_o[1] [5] = 1'b0;
  assign \density_o[1] [6] = 1'b0;
  assign \density_o[1] [7] = 1'b0;
  assign \density_o[2] [0] = 1'b0;
  assign \density_o[2] [1] = 1'b0;
  assign \density_o[2] [2] = 1'b0;
  assign \density_o[2] [3] = 1'b0;
  assign \density_o[2] [4] = 1'b0;
  assign \density_o[2] [5] = 1'b0;
  assign \density_o[2] [6] = 1'b0;
  assign \density_o[2] [7] = 1'b0;
  assign spike_o[0] = 1'b0;
  assign spike_o[1] = 1'b0;
  assign spike_o[2] = 1'b0;
  tof_delay_line_MAX_DELAY256 \G_SENS[0].u_tof (.clk (1'b0), .rst_n
       (rst_n), .clk_en (1'b0), .in_pulse (1'b0), .delay_i (8'b0),
       .out_pulse (n_13));
  tof_delay_line_MAX_DELAY256_447 \G_SENS[1].u_tof (.clk (1'b0), .rst_n
       (rst_n), .clk_en (1'b0), .in_pulse (1'b0), .delay_i (8'b0),
       .out_pulse (n_12));
  tof_delay_line_MAX_DELAY256_446 \G_SENS[2].u_tof (.clk (1'b0), .rst_n
       (rst_n), .clk_en (1'b0), .in_pulse (1'b0), .delay_i (8'b0),
       .out_pulse (n_11));
  lfsr32_2270 ux(.clk (1'b0), .rst_n (rst_n), .q (rx));
  lfsr32_2269 uy(.clk (1'b0), .rst_n (rst_n), .q (ry));
endmodule

module ai_neuron_top_comp_v2(clk, rst_n);
  input clk, rst_n;
  wire clk, rst_n;
  wire [23:0] fx_acc;
  wire [23:0] fy_acc;
  wire [5:0] syn_dst;
  wire [15:0] syn_w;
  wire [15:0] syn_addr;
  wire [5:0] syn_pre;
  wire [15:0] posx_mm;
  wire [15:0] posy_mm;
  wire [2:0] sens_spk;
  wire [7:0] \sens_rate[2] ;
  wire [7:0] \sens_rate[1] ;
  wire [7:0] \sens_rate[0] ;
  wire [7:0] \sens_dist[2] ;
  wire [7:0] \sens_dist[1] ;
  wire [7:0] \sens_dist[0] ;
  wire UNCONNECTED4, UNCONNECTED5, UNCONNECTED6, UNCONNECTED7,
       UNCONNECTED8, UNCONNECTED9, UNCONNECTED10, UNCONNECTED11;
  wire UNCONNECTED12, UNCONNECTED13, UNCONNECTED14, UNCONNECTED15,
       UNCONNECTED16, UNCONNECTED17, UNCONNECTED18, UNCONNECTED19;
  wire UNCONNECTED20, UNCONNECTED21, UNCONNECTED22, UNCONNECTED23,
       clk_en, east, goal_reached, north;
  wire south, syn_v, west;
  g_pulse_accumulator_W24 u_ax(.clk (1'b0), .rst_n (rst_n), .clk_en
       (1'b0), .plus_pulse_i (1'b0), .minus_pulse_i (1'b0), .value_o
       (fx_acc));
  g_pulse_accumulator_W24_442 u_ay(.clk (1'b0), .rst_n (rst_n), .clk_en
       (1'b0), .plus_pulse_i (1'b0), .minus_pulse_i (1'b0), .value_o
       (fy_acc));
  dynamic_synapse_processor_stream_v2_N_NEURON64_NEURON_ID_W6_WEIGHT_W16_ACC_W24_GRID_W128_GRID_H128_TOTAL_SYNAPSES4096_SYN_ADDR_W16_DEG_W12
       u_dsp(.clk (1'b0), .rst_n (rst_n), .clk_en (1'b0), .ev_valid
       (1'b0), .ev_ready (UNCONNECTED4), .pre_id_i (6'b0), .pos_x_i
       (16'b0), .pos_y_i (16'b0), .mass_u8_i (8'b1010), .syn_out_valid
       (syn_v), .syn_out_ready (1'b1), .syn_dst_id_o ({UNCONNECTED8,
       UNCONNECTED7, UNCONNECTED6, UNCONNECTED5, syn_dst[1:0]}),
       .syn_weight_o (syn_w), .syn_addr_o (syn_addr), .syn_pre_id_o
       (syn_pre), .upd_valid_i (1'b0), .upd_ready_o (UNCONNECTED9),
       .upd_addr_i (16'b0), .upd_dw_i (16'b0));
  motor_decoder_4dir u_mdec(.clk (1'b0), .rst_n (rst_n), .clk_en
       (1'b0), .ch_fire_i (4'b0), .north_o (north), .south_o (south),
       .east_o (east), .west_o (west));
  physics_integrator_2d u_phy(.clk (1'b0), .rst_n (rst_n), .clk_en
       (1'b0), .force_x_q (24'b0), .force_y_q (24'b0), .mass_g
       (6'b1010), .pos_mm_x_o ({posx_mm[15], UNCONNECTED16,
       UNCONNECTED15, UNCONNECTED14, UNCONNECTED13, UNCONNECTED12,
       UNCONNECTED11, UNCONNECTED10, posx_mm[7:0]}), .pos_mm_y_o
       ({posy_mm[15], UNCONNECTED23, UNCONNECTED22, UNCONNECTED21,
       UNCONNECTED20, UNCONNECTED19, UNCONNECTED18, UNCONNECTED17,
       posy_mm[7:0]}), .goal_reached_o (goal_reached));
  power_manager u_pwr(.clk (1'b0), .rst_n (rst_n), .clk_en_i (1'b1),
       .activity_i (1'b1), .clk_en_o (clk_en));
  pressure_sensor_field_3ch u_sens(.clk (1'b0), .rst_n (rst_n), .clk_en
       (1'b0), .reseed_i (1'b0), .pos_mm_x_i (16'b0), .pos_mm_y_i
       (16'b0), .mass_g_i (6'b1010), .spike_o (sens_spk),
       .\density_o[2]  (\sens_rate[2] ), .\density_o[1]  (\sens_rate[1]
       ), .\density_o[0]  (\sens_rate[0] ), .\dist_bin_o[2] 
       (\sens_dist[2] ), .\dist_bin_o[1]  (\sens_dist[1] ),
       .\dist_bin_o[0]  (\sens_dist[0] ));
endmodule

